"""Manuscript macros of the calendar and external-autocorrelation study.

Reads artifacts/r8_calendar/{calendar,stress_dates,external_acf}.csv and run.json; writes source/sections_r8/numbers_calendar.tex. --check compares.
"""
import argparse, hashlib, json, sys
from pathlib import Path
import pandas as pd
ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / 'artifacts/r8_calendar'; OUT = ROOT / 'source/sections_r8'

def build():
    c = pd.read_csv(ART / 'calendar.csv').set_index('series'); s = pd.read_csv(ART / 'stress_dates.csv'); e = pd.read_csv(ART / 'external_acf.csv')
    run = json.loads((ART / 'run.json').read_text())['summary']
    m = {}
    for series, tag in [('BTC', 'Btc'), ('ETH', 'Eth'), ('SP500', 'Spx'), ('GDAXI', 'Dax')]:
        r = c.loc[series]
        m[f'{tag}Obs'] = f"{int(r.observations):,}"; m[f'{tag}WeekdayMin'] = str(int(r[['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']].min())) if series in ('BTC', 'ETH') else str(int(r[['Mon', 'Tue', 'Wed', 'Thu', 'Fri']].min()))
        m[f'{tag}WeekdayMax'] = str(int(r[['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']].max()))
        m[f'{tag}Weekend'] = f"{int(r.weekend_observations):,}"; m[f'{tag}OneDayGaps'] = f"{int(r.gaps_1_day):,}"; m[f'{tag}ThreeDayGaps'] = f"{int(r.gaps_3_day):,}"
        m[f'{tag}Gaps'] = f"{int(r.gaps_total):,}"
    sun = s[s.weekday == 'Sun']; assert len(sun) == 1
    m['SundayDate'] = pd.Timestamp(sun.iloc[0].date).strftime('%-d %B %Y'); m['SundayPairs'] = str(int(sun.iloc[0].pairs_present))
    m['StressDates'] = str(len(s)); m['StressMinPairs'] = str(int(s.pairs_present.min())); m['StressFullDates'] = str(int((s.pairs_present == 240).sum()))
    covid = s[s.date == '2020-03-09']; m['CovidDatePairs'] = str(int(covid.iloc[0].pairs_present)) if len(covid) else 'NA'
    m['MinPairsPresent'] = str(run['min_pairs_present']); m['MaxPairsPresent'] = str(run['max_pairs_present']); m['DatesWithPairs'] = f"{run['dates_with_pairs']:,}"
    for uni, tag in [('devexus_25', 'DevExUs'), ('french_12', 'French')]:
        g = e[e.universe == uni]
        m[f'Acf{tag}'] = f"{g.lag1_autocorrelation.mean():.3f}"; m[f'Acf{tag}Min'] = f"{g.lag1_autocorrelation.min():.3f}"; m[f'Acf{tag}Max'] = f"{g.lag1_autocorrelation.max():.3f}"
        m[f'Acf{tag}N'] = str(len(g)); m[f'Acf{tag}Obs'] = f"{int(g.n.iloc[0]):,}"; m[f'Acf{tag}Weekend'] = str(int(g.weekend_observations.sum()))
    num = '% Generated by research/r8_calendar/displays.py; do not edit.\n' + ''.join(f'\\newcommand{{\\nCal{k}}}{{{v}}}\n' for k, v in m.items())
    return num

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    num = build(); target = OUT / 'numbers_calendar.tex'
    if a.check:
        ok = target.exists() and target.read_text() == num
        print(json.dumps(dict(status='pass' if ok else 'FAIL'))); sys.exit(0 if ok else 1)
    target.write_text(num)
    rec = dict(inputs={n: hashlib.sha256((ART / n).read_bytes()).hexdigest() for n in ['calendar.csv', 'stress_dates.csv', 'external_acf.csv', 'run.json']},
               outputs={target.name: hashlib.sha256(num.encode()).hexdigest()})
    (ART / 'displays.json').write_text(json.dumps(rec, indent=2) + '\n'); print('written')
if __name__ == '__main__': main()
