"""Exact manuscript values from the verified information experiment."""
import argparse
import hashlib
import json
from pathlib import Path
import tempfile
import pandas as pd

ROOT=Path(__file__).resolve().parents[2]
SOURCE=ROOT/'source'
OUT=ROOT/'artifacts/r8_information_integration'
INPUT='artifacts/r8_information_limit/run/finite.csv'


def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def build(destination):
    d=pd.read_csv(ROOT/INPUT)
    d=d[(d.alpha==.01)&(d.epsilon==.2)&(d.n==250)].set_index('retention')
    assert len(d)==4
    macros=dict(nInfoThetaLow=f'{100*d.loc[0,"theta0"]:.3f}',
                nInfoThetaHigh=f'{100*d.loc[0,"theta1"]:.3f}',
                nInfoErrorIid=f'{100*d.loc[0,"best_average_error"]:.1f}',
                nInfoErrorDependent=f'{100*d.loc[.5,"best_average_error"]:.1f}')
    path=destination/'sections_r8/numbers_information.tex';path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text('% Generated by research/r8_information_integration/build.py.\n'+
                    '\n'.join('\\newcommand{\\'+k+'}{'+v+'}' for k,v in sorted(macros.items()))+'\n')
    return dict(producer_sha256=sha(__file__),inputs={INPUT:sha(ROOT/INPUT)},
                outputs={'sections_r8/numbers_information.tex':sha(path)},macros=macros)


def verify(manifest):
    assert manifest['producer_sha256']==sha(__file__)
    for name,h in manifest['inputs'].items():assert sha(ROOT/name)==h,name
    for name,h in manifest['outputs'].items():assert sha(SOURCE/name)==h,name


def check():
    m=json.loads((OUT/'displays.json').read_text());verify(m)
    bad=json.loads(json.dumps(m));bad['outputs']['sections_r8/numbers_information.tex']='0'*64
    try:verify(bad)
    except AssertionError:pass
    else:raise AssertionError('Output corruption control failed')
    with tempfile.TemporaryDirectory(prefix='irfa-info-display-') as folder:assert build(Path(folder))==m
    return dict(exact_display_replay=1,negative_control=True)


if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
    if args.check:print(json.dumps(check()))
    else:
        OUT.mkdir(parents=True,exist_ok=True)
        (OUT/'displays.json').write_text(json.dumps(build(SOURCE),indent=2)+'\n')
