#!/usr/bin/env python3
"""Generate R8 displays and prose numbers from the complete August archive."""
import hashlib
import json
import os
os.environ.setdefault('MPLCONFIGDIR','/private/tmp/irfa-august-mpl')
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.colors import ListedColormap
from matplotlib.patches import Patch
from commodity_scope import ROOT,MODELS,N_PAIRS,CLASSES
from analyse_panel import METHODS

SOURCE=Path(__file__).resolve().parents[2];OUT=SOURCE/'sections_r8';FIG=SOURCE/'figures'
LABEL={'Raw':'Raw forecast','Conformal':'Static conformal','Scale':'Multiplicative scale',
       'QR-Residual':'Affine quantile regression','Hist-Quantile':'Historical quantile','Isotonic':'Isotonic quantile regression',
       'aci':'ACI','rolling':'Rolling conformal','gamlss':'GAMLSS-SST','gbm':'Boosted quantile regression',
       'Gate-static':'Static on indication','Gate-rolling':'Rolling on indication'}


def table(name,headers,rows,fmt=None):
    text='% Generated by build_paper_outputs.py; do not edit.\n'
    text+='\\begin{tabular}{'+(fmt or 'l'+'r'*(len(headers)-1))+'}\n\\toprule\n'
    text+=' & '.join(headers)+r' \\'+'\n\\midrule\n'
    text+='\n'.join(' & '.join(map(str,row))+r' \\' for row in rows)
    text+='\n\\bottomrule\n\\end{tabular}\n';(OUT/name).write_text(text)


def traffic_light_figure(methods):
    """Show the same selected per-pair diagnostics used in the method table."""
    models=['EWMA','GARCH-N','GJR-GARCH','GJR-GARCH-t','Hist-Sim',
            'Lag-Llama','Moirai-1.1']
    assets=[a for group in CLASSES.values() for a in group]
    zones=['Green','Yellow','Red'];colors=['#00AD70','#FFCC00','#F04438']
    cmap=ListedColormap(colors)
    fig,axes=plt.subplots(2,1,figsize=(9.4,7.0),sharex=True)
    for ax,method,title in zip(axes,['Raw','Conformal'],['(a) Raw forecasts','(b) Static conformal correction']):
        d=methods[methods.method==method].set_index(['model','asset'])
        assert len(d)==N_PAIRS and not d.index.has_duplicates
        values=np.array([[zones.index(d.loc[(m,a),'TL']) for a in assets] for m in models])
        ax.imshow(values,cmap=cmap,vmin=0,vmax=2,aspect='auto',interpolation='nearest')
        ax.set_yticks(range(len(models)),models,fontsize=13)
        ax.set_xticks(range(len(assets)),assets,rotation=60,ha='right',fontsize=11.5)
        ax.tick_params(axis='both',length=0,pad=5)
        ax.set_title(title,loc='left',fontsize=14,fontweight='bold',pad=38)
        counts=[int((values==z).sum()) for z in range(3)]
        ax.text(1,1.13,' / '.join(f'{n} {z}' for n,z in zip(counts,zones)),
                transform=ax.transAxes,ha='right',fontsize=11,color='#4a4a4a')
        start=0
        for name,group in CLASSES.items():
            end=start+len(group)
            ax.text((start+(len(group)-1)/2)/len(assets)+.5/len(assets),1.02,
                    {'Bond ETF':'Bond ETFs','Commodity':'Commodities'}.get(name,name),
                    transform=ax.transAxes,ha='center',fontsize=10.5,color='#555555')
            if start:ax.axvline(start-.5,color='white',lw=2)
            start=end
        for y in np.arange(.5,len(models)-.5):ax.axhline(y,color='white',lw=.3,alpha=.6)
        for spine in ax.spines.values():spine.set_visible(False)
    thresholds=[r'$e\leq4$',r'$4<e\leq9$',r'$e>9$']
    handles=[Patch(facecolor=c,label=label) for c,label in zip(colors,thresholds)]
    fig.legend(handles=handles,loc='lower center',bbox_to_anchor=(.5,.01),
               ncol=3,frameon=False,fontsize=14,
               title='Equivalent violations per 250 observations ($e$)',title_fontsize=12)
    fig.subplots_adjust(left=.19,right=.985,top=.86,bottom=.25,hspace=.60)
    fig.savefig(FIG/'fig_traffic_light_august.pdf',transparent=True,
                metadata={'CreationDate':None,'ModDate':None})
    plt.close(fig)


def rolling_figure(read):
    """Recover rolling shifts from saved forecasts; do not refit a model."""
    models=['Moirai-1.1','Lag-Llama','GJR-GARCH']
    colors=['#FF7900','#00A889','#0066FF']
    styles=['-.','-',':']
    series={}
    for model in models:
        d=read(f'posthoc/{model}__SP500.parquet')
        assert d.index.is_unique and d.index.is_monotonic_increasing
        assert np.array_equal(d.Raw,d['raw_0.01'])
        assert np.array_equal(d['rolling'],d['rolling_0.01'])
        series[model]=d.Raw-d['rolling']
    dates=series[models[0]].index
    for s in series.values():dates=dates.intersection(s.index)
    assert dates[-1]==pd.Timestamp('2026-08-31')
    frame=pd.DataFrame({m:s.loc[dates] for m,s in series.items()})*100
    assert np.isfinite(frame.to_numpy()).all()
    fig,axes=plt.subplots(2,1,figsize=(9.4,7.0),sharey=True)
    detail=frame.loc['2020-01-01':'2021-06-30']
    for ax,data,title in zip(axes,[frame,detail],
                           ['(a) S&P 500: shared test dates','(b) Detail around the COVID-19 shock']):
        for model,color,style in zip(models,colors,styles):
            ax.step(data.index,data[model],where='post',color=color,ls=style,
                    lw=1.35,label=model)
        ax.axhline(0,color='#777777',lw=.7,ls='--')
        ax.axvspan(pd.Timestamp('2020-02-20'),pd.Timestamp('2020-04-30'),
                   color='#FF7900',alpha=.10,lw=0)
        ax.set_xlim(data.index[0],data.index[-1])
        ax.set_title(title,loc='left',fontsize=14,fontweight='bold',pad=12)
        ax.set_ylabel('Rolling shift\n(log return ×100)',fontsize=13)
        ax.tick_params(labelsize=13)
        ax.grid(axis='y',alpha=.15)
    axes[0].xaxis.set_major_locator(mdates.YearLocator())
    axes[0].xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    axes[1].xaxis.set_major_locator(mdates.MonthLocator(interval=3))
    axes[1].xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))
    handles,labels=axes[0].get_legend_handles_labels()
    fig.legend(handles,labels,loc='lower center',bbox_to_anchor=(.5,.01),
               ncol=3,frameon=False,fontsize=12)
    fig.subplots_adjust(left=.115,right=.985,top=.92,bottom=.15,hspace=.44)
    fig.savefig(FIG/'fig_rolling_august.pdf',transparent=True,
                metadata={'CreationDate':None,'ModDate':None})
    plt.close(fig)


def complexity_outputs(read,mac):
    """Controlled mechanism experiment: matched pinball-loss regressions."""
    data=read('results/review/complexity_mc.csv')
    assert len(data)==224 and not data.duplicated(['innovation','truth','n_cal','alpha','method']).any()
    methods=['Shift-ERM','State2-ERM','State4-ERM']
    labels=['1 coefficient','2 coefficients','4 coefficients']
    colors=['#0066FF','#FF7900','#8A2BE2'];markers=['o','s','^']
    fig,axes=plt.subplots(2,2,figsize=(9.4,7.1),sharex=True,sharey=True)
    for i,kind in enumerate(['normal','t5']):
        for j,truth in enumerate(['constant','state']):
            ax=axes[i,j]
            group=data[(data.innovation==kind)&(data.truth==truth)&(data.alpha==.01)]
            for method,label,color,marker in zip(methods,labels,colors,markers):
                values=group[group.method==method].sort_values('n_cal')
                ax.errorbar(values.n_cal,values.mean_excess_QS*1e4,
                            yerr=1.96*values.excess_QS_MCSE*1e4,
                            color=color,marker=marker,lw=1.5,ms=4,capsize=2,label=label)
            raw=group[group.method=='Raw'].mean_excess_QS.iloc[0]*1e4
            ax.axhline(raw,color='#626262',ls=':',lw=1.3,label='Raw forecast')
            law='Normal' if kind=='normal' else 'Student-t(5)'
            shape='constant distortion' if truth=='constant' else 'state-dependent distortion'
            ax.set_title(f'({"abcd"[i*2+j]}) {law}: {shape}',loc='left',fontsize=12,fontweight='bold',pad=10)
            ax.set_xscale('log');ax.set_yscale('log');ax.grid(alpha=.15)
            ax.set_xticks([125,250,500,1000],['125','250','500','1,000'])
            ax.set_xlim(100,1250)
            ax.set_xlabel('Calibration observations',fontsize=12)
            if j==0:ax.set_ylabel('Excess expected QS (×10⁴)',fontsize=12)
    handles,legend=axes[0,0].get_legend_handles_labels()
    fig.legend(handles,legend,loc='lower center',bbox_to_anchor=(.5,.01),ncol=4,frameon=False,fontsize=12)
    fig.tight_layout(rect=(0,.07,1,1),h_pad=1.3,w_pad=1.2)
    fig.savefig(FIG/'fig_complexity_august.pdf',transparent=True,metadata={'CreationDate':None,'ModDate':None})
    plt.close(fig)
    # A compact supplementary comparison reports both target levels and
    # both distortion shapes; all seven candidates remain in the CSV archive.
    rows=[]
    for kind,label in [('normal','Normal'),('t5',r'$t_5$')]:
        for alpha in [.01,.05]:
            for n in [125,250,500,1000]:
                group=data[(data.innovation==kind)&(data.alpha==alpha)&(data.n_cal==n)]
                record=[label,f'{100*alpha:g}\\%',n]
                for truth in ['constant','state']:
                    indexed=group[group.truth==truth].set_index('method')
                    record += [f'{indexed.loc[m,"mean_excess_QS"]*1e4:.3f}' for m in methods]
                rows.append(record)
    table('tab_complexity_mc.tex',['Innovation',r'$\alpha$','$n$',r'Const.: $p=1$',r'$p=2$',r'$p=4$',
                                   r'State: $p=1$',r'$p=2$',r'$p=4$'],rows,'llrrrrrrr')
    normal=data[(data.innovation=='normal')&(data.truth=='constant')&(data.alpha==.01)&(data.n_cal==125)].set_index('method')
    mac['ComplexityVarianceRatio']=f'{normal.loc["State4-ERM","integrated_variance"]/normal.loc["Shift-ERM","integrated_variance"]:.1f}'
    return 'complexity'


def review_outputs(read,mac):
    full=read('results/review/full_summary.csv')
    ci=read('results/review/paired_intervals.csv')
    family=['Raw','Shift-CP','Shift-ERM','Vol-CP','Vol-ERM','State2-ERM','State4-ERM']
    counts=[0,1,1,1,1,2,4]
    allrows=full[(full.alpha==.01)&(full.state=='All')].set_index('method')
    rows=[]
    for name,p in zip(family,counts):
        r=allrows.loc[name];intervals=[]
        for length in [20,60]:
            if name=='Shift-CP':intervals.append('--');continue
            c=ci[(ci.comparator==name)&(ci.reference=='Shift-CP')&(ci.block_calendar_days==length)].iloc[0]
            intervals.append(f'[{c.simultaneous_lower:.3f}, {c.simultaneous_upper:.3f}]')
        rows.append([name,p,f'{r.QS*1e4:.3f}',f'{r.violation_rate*100:.2f}']+intervals)
    table('tab_controlled_full.tex',['Correction','$p$','QS',r'$\bar\pi$ (\%)','20-day band','60-day band'],rows,'lrrrrr')
    for name,tag in [('Vol-CP','VolCp'),('Vol-ERM','VolErm'),('State2-ERM','StateTwo'),('State4-ERM','StateFour')]:
        mac[tag+'QS']=f'{allrows.loc[name,"QS"]*1e4:.2f}'
    c=ci[(ci.comparator=='Vol-ERM')&(ci.reference=='Shift-CP')&(ci.block_calendar_days==20)].iloc[0]
    mac.update(VolDifference=f'{c.difference:.3f}',VolSimLower=f'{c.simultaneous_lower:.3f}',VolSimUpper=f'{c.simultaneous_upper:.3f}')
    sweep=read('results/review/sweep_summary.csv');rows=[]
    for alpha in [.01,.025,.05,.1]:
        for n in [125,250,500,1000]:
            d=sweep[(sweep.alpha==alpha)&(sweep.n_cal==n)].set_index('method')
            rows.append([f'{alpha*100:g}\\%',n]+[f'{d.loc[m,"QS"]*1e4:.2f}' for m in family])
    table('tab_controlled_sweep.tex',[r'$\alpha$','$n$','Raw','Shift-CP','Shift-ERM','Vol-CP','Vol-ERM','State2','State4'],rows,'lrrrrrrrr')
    rows=[]
    for method in family:
        d=full[(full.alpha==.01)&(full.method==method)].set_index('state')
        rows.append([method]+[f'{d.loc[s,"QS"]*1e4:.2f}' for s in ['High','Other']]+
                    [f'{d.loc[s,"violation_rate"]*100:.2f}' for s in ['High','Other']]+
                    [f'{d.loc[s,"mean_absolute_threshold"]*100:.2f}' for s in ['High','Other']])
    table('tab_controlled_states.tex',['Correction','QS high','QS other',r'$\pi$ high',r'$\pi$ other',r'$|q|$ high',r'$|q|$ other'],rows)
    state=full[(full.alpha==.01)&(full.method=='Raw')].set_index('state')
    mac.update(HighPairs=str(int(state.loc['High','pairs'])),HighRows=f'{int(state.loc["High","test_observations"]):,}',
               OtherRows=f'{int(state.loc["Other","test_observations"]):,}')
    policies=read('results/review/policies_summary.csv');pairs=read('results/review/policies_pairs.csv')
    order=['Raw','Static','Gate-static','Rolling125','Gate-rolling125','Rolling250','Gate-rolling250',
           'Rolling500','Gate-rolling500','Selected-rolling','Gate-selected-rolling']
    labels=['Raw','Static','Static on indication','Rolling 125','Rolling 125 on indication','Rolling 250',
            'Rolling 250 on indication','Rolling 500','Rolling 500 on indication','Selected window','Selected window on indication']
    d=policies[(policies.origin=='Original')&(policies.state=='All')].set_index('method')
    original=pairs[(pairs.origin=='Original')&(pairs.state=='All')]
    raw=original[original.method=='Raw'].set_index(['model','asset']).QS;rows=[]
    for method,label in zip(order,labels):
        r=d.loc[method];individual=original[original.method==method].set_index(['model','asset']).QS
        rows.append([label,f'{r.QS*1e4:.2f}',f'{r.violation_rate*100:.2f}',int(r.kupiec_rejections),int((individual>raw).sum())])
    table('tab_policy.tex',['Policy','QS',r'$\bar\pi$ (\%)','UC','Deteriorations'],rows)
    rows=[]
    for method,label in zip(order,labels):
        p=policies[(policies.method==method)&(policies.state=='All')].set_index('origin')
        rows.append([label]+[f'{p.loc[f"Origin{o}","QS"]*1e4:.2f}' for o in [50,60,70,80]])
    table('tab_policy_origins.tex',['Policy',r'50\% origin',r'60\%',r'70\%',r'80\%'],rows)
    for name,tag in [('Rolling500','RollingLong'),('Selected-rolling','Selected'),('Gate-selected-rolling','GateSelected')]:
        mac[tag+'QS']=f'{d.loc[name,"QS"]*1e4:.2f}'
    decisions=read('results/review/decisions.csv');counts=decisions[decisions.origin=='Original'].window.value_counts()
    for n,tag in [(125,'Short'),(250,'Mid'),(500,'Long')]:mac['Selected'+tag]=str(int(counts[n]))
    selected=ci[(ci.comparator=='Gate-selected-rolling')&(ci.reference=='Selected-rolling')&(ci.block_calendar_days==20)].iloc[0]
    mac.update(SelectedGateDifference=f'{selected.difference:.3f}',SelectedGateLower=f'{selected.lower:.3f}',SelectedGateUpper=f'{selected.upper:.3f}')
    calendar=read('results/review/calendar_scores.csv');d=calendar[calendar.alpha==.01].groupby(['interface','method']).QS.mean()*1e4
    rows=[]
    for mode in ['Legacy-sampled','Actual-sampled','Legacy-law','Actual-law']:
        rows.append([mode,f'{d.loc[(mode,"Raw")]:.3f}',f'{d.loc[(mode,"Static")]:.3f}'])
    table('tab_calendar.tex',['Interface','QS raw','QS static'],rows)


def main():
    if not (ROOT/'primary_ready.json').exists():raise RuntimeError('Unfiltered primary inputs have not been promoted')
    OUT.mkdir(exist_ok=True);FIG.mkdir(exist_ok=True);mac={};inputs={}
    def read(name):
        p=ROOT/name;inputs[name]=hashlib.sha256(p.read_bytes()).hexdigest()
        return pd.read_parquet(p) if p.suffix=='.parquet' else pd.read_csv(p)
    methods=read('results/posthoc.csv');ind=read('results/indication.csv');ind=ind[ind.alpha==.01]
    assert len(methods)==N_PAIRS*10 and len(ind)==N_PAIRS
    mac.update(Pairs=str(N_PAIRS),Models=str(len(MODELS)))
    avg=methods.groupby('method').agg(QS=('QS','mean'),pi=('pihat','mean'),width=('width','mean'),
        kup=('p_kup',lambda s:(s<.05).sum()),cc=('p_cc',lambda s:(s<.05).sum()),ccn=('p_cc','count'),green=('TL',lambda s:(s=='Green').sum()))
    table('tab_methods.tex',['Method',r'QS',r'$\bar\pi$ (\%)','UC','CC','Green',r'$|q|$'],[
        [LABEL[m],f'{avg.loc[m,"QS"]*1e4:.2f}',f'{avg.loc[m,"pi"]*100:.2f}',int(avg.loc[m,'kup']),
         str(int(avg.loc[m,'cc']))+(f'/{int(avg.loc[m,"ccn"])}' if avg.loc[m,'ccn']<N_PAIRS else ''),int(avg.loc[m,'green']),f'{avg.loc[m,"width"]*100:.2f}']
        for m in ['Raw','Conformal','Scale','QR-Residual','Isotonic','Hist-Quantile','aci','rolling','gamlss','gbm']])
    for tag,m in [('Raw','Raw'),('Static','Conformal'),('Scale','Scale'),('Qr','QR-Residual'),('Aci','aci'),('Rolling','rolling')]:
        mac[tag+'QS']=f'{avg.loc[m,"QS"]*1e4:.2f}';mac[tag+'Pi']=f'{avg.loc[m,"pi"]*100:.2f}';mac[tag+'Kup']=str(int(avg.loc[m,'kup']))
    common=read('results/common_support.csv');rows=[]
    for m in list(MODELS)+['CAViaR-SAV','CAViaR-AS','GAS-t','EVT-POT','FHS']:
        d=common[common.model==m];a=d[d.method=='Raw'];b=d[d.method=='Conformal']
        rows.append([m,f'{a.QS.mean()*1e4:.2f}',f'{b.QS.mean()*1e4:.2f}' if len(b) else '--',
                     f'{100*a.pihat.mean():.2f}',f'{100*b.pihat.mean():.2f}' if len(b) else '--',
                     int((a.p_kup<.05).sum()),str(int((b.p_kup<.05).sum())) if len(b) else '--'])
    table('tab_forecasters.tex',['Forecaster','QS raw','QS static',r'$\pi$ raw',r'$\pi$ static','UC raw','UC static'],rows)
    pol=read('results/policy.csv');pavg=pol.groupby('method').QS.mean();raw=pol[pol.method=='Raw'].set_index(['model','asset']).QS
    rows=[]
    for m in ['Raw','Conformal','Gate-static','rolling','Gate-rolling']:
        d=pol[pol.method==m].set_index(['model','asset']);diff=d.QS-raw
        rows.append([LABEL[m],f'{d.QS.mean()*1e4:.2f}',f'{100*d.pihat.mean():.2f}',int((d.TL=='Green').sum()),int((diff>0).sum())])
    table('tab_policy.tex',['Policy','QS',r'$\bar\pi$ (\%)','Green','Deteriorations'],rows)
    gate=(ind.p_kup_cal<.05)|(ind.TL_cal!='Green');well=ind.p_kup_raw>=.05
    mac.update(GateApplied=str(int(gate.sum())),GateSkipped=str(int((~gate).sum())),WellN=str(int(well.sum())),
               GateStaticQS=f'{pavg["Gate-static"]*1e4:.2f}',GateRollingQS=f'{pavg["Gate-rolling"]*1e4:.2f}')
    for tag,col in [('Static','static'),('Rolling','roll')]:
        diff=ind['dQS_'+col];mac[tag+'WellWorse']=str(int(((diff<0)&well).sum()))
        mac[tag+'Avoided']=str(int(((diff<0)&~gate).sum()));mac[tag+'Forgone']=str(int(((diff>0)&~gate).sum()))
    ci=read('results/paired_loss_intervals.csv');c=ci[(ci.comparator=='Scale')&(ci.reference=='Conformal')&(ci.block_calendar_days==20)].iloc[0]
    mac.update(ScaleDifference=f'{c.difference:.3f}',ScaleCILower=f'{c.lower:.3f}',ScaleCIUpper=f'{c.upper:.3f}')
    gate_ci=ci[(ci.comparator=='Gate-static')&(ci.reference=='Conformal')&(ci.block_calendar_days==20)].iloc[0]
    mac.update(GateStaticDifference=f'{gate_ci.difference:.4f}',GateStaticLower=f'{gate_ci.lower:.4f}',GateStaticUpper=f'{gate_ci.upper:.4f}')
    cid=ci.drop_duplicates(['comparator','reference','block_calendar_days']);rows=[]
    for (m,ref),g in cid.groupby(['comparator','reference'],sort=False):
        a=g[g.block_calendar_days==20].iloc[0];b=g[g.block_calendar_days==60].iloc[0]
        rows.append([LABEL[m]+' -- '+LABEL[ref],f'{a.difference:.3f}',f'[{a.lower:.3f}, {a.upper:.3f}]',f'[{b.lower:.3f}, {b.upper:.3f}]'])
    table('tab_intervals.tex',['Loss difference','Mean','20-day interval','60-day interval'],rows,'lrrr')
    plot=ci[(ci.reference=='Conformal')&(ci.block_calendar_days==20)&ci.comparator.isin(METHODS)].drop_duplicates('comparator').iloc[::-1]
    plt.rcParams.update({'font.family':'DejaVu Sans','font.size':12,'axes.spines.top':False,'axes.spines.right':False,
                         'figure.facecolor':'none','axes.facecolor':'none'})
    traffic_light_figure(methods)
    rolling_figure(read)
    fig,ax=plt.subplots(figsize=(7.8,4.7));yy=np.arange(len(plot))
    interval=ax.hlines(yy,plot.lower,plot.upper,color='#1A73E8',linewidth=2,label='95% pointwise interval')
    estimate=ax.scatter(plot.difference,yy,color='#7C3AED',s=30,zorder=3,label='Mean loss difference')
    ax.axvline(0,color='.5',lw=1,ls='--');ax.set_yticks(yy,[LABEL[x] for x in plot.comparator]);ax.set_xlabel('Comparator loss minus static conformal loss (×10⁴)')
    ax.grid(axis='x',alpha=.15)
    fig.legend(handles=[estimate,interval],loc='lower center',bbox_to_anchor=(.5,.01),ncol=2,frameon=False,fontsize=11)
    fig.tight_layout(rect=(0,.13,1,1))
    fig.savefig(FIG/'fig_loss_august.pdf',transparent=True,metadata={'CreationDate':None,'ModDate':None});plt.close(fig)
    gaps=read('results/gaps.csv');b=gaps[gaps.variant=='Contiguous'].set_index(['model','asset']);g=gaps[gaps.variant=='Full proxy'].set_index(['model','asset'])
    mac.update(GapShare=f'{100*(g.gap/g.n_original_test).median():.1f}',GapZones=str(int((g.TL!=b.TL).sum())),GapPiChange=f'{(g.pihat-b.pihat).abs().median():.4f}')
    rows=[]
    for v,d in gaps.groupby('variant',sort=False):
        z=d.set_index(['model','asset']);rows.append([v,f'{z.gap.median():.0f}',f'{100*(z.gap/z.n_original_test).median():.1f}',f'{100*z.pihat.mean():.2f}',int((z.TL!=b.TL).sum())])
    table('tab_gaps.tex',['Design','Median gap',r'Removed (\%)',r'$\bar\pi$ (\%)','Zone changes'],rows)
    windows=read('results/windows.csv');rows=[]
    for w,d in windows.groupby('w'):rows.append([w,int(d.k.iloc[0]),f'{d.effective_rank.iloc[0]:.3f}',f'{d.QS.mean()*1e4:.2f}',f'{100*d.pihat.mean():.2f}',int((d.p_kup<.05).sum())])
    table('tab_windows.tex',['Window','Rank','Rank level','QS',r'$\bar\pi$ (\%)','UC'],rows)
    sens=read('results/class_sensitivity.csv');sens.excluded_class=sens.excluded_class.fillna('None');rows=[]
    for m in METHODS:
        d=sens[sens.method==m].set_index('excluded_class');rows.append([LABEL[m]]+[f'{d.loc[x,"QS"]*1e4:.2f}' for x in ['None','Equity','Bond ETF','Commodity','Crypto','FX']]+[f'{d.loc["None","normalised_QS"]:.4f}'])
    table('tab_classes.tex',['Method','All','No eq.','No bonds','No comm.','No crypto','No FX','Scaled'],rows)
    quote=read('results/quotation_period_summary.csv');rows=[]
    for m in METHODS:
        d=quote[quote.method==m].set_index('variant')
        rows.append([LABEL[m]]+[f'{d.loc[v,"QS"]*1e4:.2f}' for v in ['All','2026 only','Exclude UNG','Exclude commodity funds']])
    table('tab_quotations.tex',['Method','All','2026','No UNG','No commodity funds'],rows)
    dq=read('results/dq_diagnostics.csv');rows=[]
    for m in METHODS:
        d=dq[dq.method==m];rows.append([LABEL[m],int(d.p_DQ.notna().sum()),int((d.p_DQ<.05).sum())])
    table('tab_dq.tex',['Method','Defined tests','Rejections at 5\\%'],rows)
    mac.update(StaticDQ=str(int(((dq.method=='Conformal')&(dq.p_DQ<.05)).sum())),RawDQ=str(int(((dq.method=='Raw')&(dq.p_DQ<.05)).sum())))
    draws=read('results/predictive_sampling/draws.csv');d=draws[draws.n==1000]
    mac.update(DrawSdMin=f'{100*d.sd_over_VaR_median.min():.1f}',DrawSdMax=f'{100*d.sd_over_VaR_median.max():.1f}')
    table('tab_draws.tex',['Model','Asset',r'$N$',r'Daily SD / VaR (\%)','Daily SD / shift',r'Bias / VaR (\%)'],[
        [r.model,r.asset,r.n,f'{100*r.sd_over_VaR_median:.1f}',f'{r.sd_over_qV_median:.2f}',f'{100*r.bias_over_VaR_median:.2f}'] for r in draws.itertuples()],'llrrrr')
    prop=read('results/predictive_sampling/propagation.csv')
    table('tab_propagation.tex',['Model','Asset',r'$N$','Cal. size','SD / shift',r'95\% deviation / shift'],[
        [r.model,r.asset,r.n,r.n_cal,f'{r.sd_over_qV:.2f}',f'{r.p95_absdev_over_qV:.2f}'] for r in prop.itertuples()],'llrrrr')
    inv=read('quality/asset_inventory.csv');classes={a:c for c,aa in CLASSES.items() for a in aa};rows=[]
    for r in inv.sort_values('asset').itertuples():rows.append([r.asset,classes[r.asset],r.currency,r.n_returns,r.first_date+' -- '+r.last_date])
    table('tab_assets.tex',['Series','Class','Currency',r'$T$','Return period'],rows,'lllrl')
    mc=read('results/monte_carlo/grid.csv');order=['normal','t5','t3','skewt3','mixnormal'];names=['Normal',r'$t_5$',r'$t_3$',r'Skewed $t_3$','Mixture'];rows=[]
    for dgp,label in zip(order,names):
        for r in mc[mc.dgp==dgp].sort_values('T').itertuples():rows.append([label,r.T,f'{r.Raw_pi:.4f}',f'{r.Corr_pi:.4f}',f'{r.Mean_qV:.5f}',f'{r.Std_qV:.5f}',f'{r.DQS_mean*1e4:.3f}',f'{r.DQS_se*1e4:.3f}'])
    table('tab_mc.tex',['Innovation',r'$T$',r'$\pi$ raw',r'$\pi$ static','Mean shift','SD shift',r'$\Delta$QS',r'SE($\Delta$QS)'],rows)
    fig,axes=plt.subplots(2,2,figsize=(9.4,7.4));colors=['#0066FF','#E8325A','#00A86B','#8A2BE2','#FF8C00']
    for dgp,label,color,marker in zip(order,['Normal','t(5)','t(3)','Skewed t(3)','Mixture'],colors,['o','s','^','D','v']):
        d=mc[mc.dgp==dgp].sort_values('T')
        for ax,values in zip(axes.flat,[d.Corr_pi*100,d.DQS_mean*1e4,d.RawGreen,d.Std_qV*100]):
            ax.plot(d['T'],values,marker=marker,color=color,label=label,ms=4,lw=1.5)
    axes[0,0].axhline(1,color='.5',lw=1,ls='--');axes[0,1].axhline(0,color='.5',lw=1,ls='--')
    titles=['(a) Marginal coverage','(b) Gain in Quantile Score',
            '(c) Raw forecasts in Green','(d) Shift dispersion']
    labels_y=['Corrected violation rate (%)','Raw minus static QS (×10⁴)',
              'Replications in Green (%)','SD of shift (log return ×100)']
    for ax,title,ylabel in zip(axes.flat,titles,labels_y):
        ax.set_xscale('log');ax.set_xlabel('Retained sample size',fontsize=13);ax.grid(alpha=.15)
        ax.set_xticks([500,1000,2000,5000,10000],['500','1,000','2,000','5,000','10,000'])
        ax.tick_params(axis='x',labelsize=11.5)
        ax.set_ylabel(ylabel,fontsize=13);ax.set_title(title,loc='left',fontsize=14,fontweight='bold',pad=10)
    axes[1,0].set_ylim(-2,102);axes[1,1].set_yscale('log')
    handles,labels=axes[0,0].get_legend_handles_labels()
    fig.legend(handles,labels,loc='lower center',bbox_to_anchor=(.5,.01),ncol=5,frameon=False,fontsize=13)
    fig.tight_layout(rect=(0,.07,1,1),h_pad=1.7,w_pad=1.5)
    fig.savefig(FIG/'fig_mc_august.pdf',transparent=True,metadata={'CreationDate':None,'ModDate':None});plt.close(fig)
    additional=[]
    if (ROOT/'results/review/complexity_mc.csv').exists():
        additional.append(complexity_outputs(read,mac))
    if (ROOT/'results/review/full_summary.csv').exists():
        review_outputs(read,mac)
    tex='% Generated exclusively from August primary inputs.\n'+''.join('\\newcommand{\\nAug'+k+'}{'+v+'}\n' for k,v in mac.items())
    tex+='\\newcommand{\\nLitLambdaTail}{1.9\\times10^{-7}}\n\\newcommand{\\nTheoryNCal}{700}\n\\newcommand{\\nTheoryConfIndex}{0.9914}\n'
    (OUT/'numbers_august.tex').write_text(tex)
    # Explicit output ownership prevents absorbing tables from other producers.
    own_table_names = {
        'tab_assets.tex',
        'tab_calendar.tex',
        'tab_classes.tex',
        'tab_complexity_mc.tex',
        'tab_controlled_full.tex',
        'tab_controlled_states.tex',
        'tab_controlled_sweep.tex',
        'tab_dq.tex',
        'tab_draws.tex',
        'tab_forecasters.tex',
        'tab_gaps.tex',
        'tab_intervals.tex',
        'tab_mc.tex',
        'tab_methods.tex',
        'tab_policy.tex',
        'tab_policy_origins.tex',
        'tab_propagation.tex',
        'tab_quotations.tex',
        'tab_windows.tex',
    }
    own_tables=[p for p in OUT.glob('tab_*.tex') if p.name in own_table_names]
    outputs={str(p.relative_to(SOURCE)):hashlib.sha256(p.read_bytes()).hexdigest() for p in own_tables+[OUT/'numbers_august.tex']+[FIG/f'fig_{name}_august.pdf' for name in ['loss','mc','traffic_light','rolling']+additional]}
    scope_sha=hashlib.sha256(Path(__file__).with_name('commodity_scope.py').read_bytes()).hexdigest()
    (ROOT/'results/paper_outputs_manifest.json').write_text(json.dumps(dict(producer_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),scope_sha256=scope_sha,inputs=inputs,outputs=outputs,macros=mac),indent=2)+'\n')
    print('R8 displays and numbers generated from complete primary panel',flush=True)


if __name__=='__main__':main()
