"""Deterministic manuscript displays from the validated partial-shift study.

No new fitting or simulation. Check regenerates every display and exercises
an output-corruption negative control.
"""
import argparse
import hashlib
import json
from pathlib import Path
import tempfile
import pandas as pd

PROJECT = Path(__file__).resolve().parents[2]
SOURCE = PROJECT / 'source'
OUT = PROJECT / 'artifacts/r8_partial_integration'
INPUTS = ['artifacts/r8_partial_shift/run/summary.csv',
          'artifacts/r8_partial_shift/run/decomposition.csv']
METHODS = ['Raw', 'Full-CP', 'Half-Full', 'Inner-CP', 'Half-Inner',
           'Selected-Inner', 'Oracle-Grid', 'Oracle-Continuous']


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def build(destination):
    summary = pd.read_csv(PROJECT / INPUTS[0])
    decomposition = pd.read_csv(PROJECT / INPUTS[1])
    assert len(summary) == 144 * 8 and summary.histories.eq(500).all()
    assert len(decomposition) == 144
    macros = {}
    grouped = summary.groupby(['alpha', 'method']).agg(
        loss=('expected_loss', 'mean'), violation=('expected_violation', 'mean'))
    for alpha, tag in [(.01, 'One'), (.05, 'Five')]:
        selected = summary[(summary.alpha == alpha) & (summary.method == 'Selected-Inner')]
        assert len(selected) == 72
        for reference, name in [('Raw', 'Raw'), ('Full-CP', 'Full'), ('Half-Inner', 'Half')]:
            macros['nPartial' + tag + 'Better' + name] = str(int((selected['difference_vs_' + reference] < 0).sum()))
        d = decomposition[decomposition.alpha == alpha]
        ratio = 100 * d.selection_regret.mean() / d.oracle_shrinkage_gain.mean()
        macros['nPartial' + tag + 'RegretPct'] = f'{ratio:.1f}'
    lines = [r'\begin{tabular}{lrrrr}', r'\toprule',
             r'& \multicolumn{2}{c}{1\% tail} & \multicolumn{2}{c}{5\% tail} \\',
             r'\cmidrule(lr){2-3}\cmidrule(lr){4-5}',
             r'Method & Expected QS & Viol. (\%) & Expected QS & Viol. (\%) \\', r'\midrule']
    for method in METHODS:
        if method == 'Oracle-Grid':
            lines.append(r'\midrule')
        values = []
        for alpha in [.01, .05]:
            row = grouped.loc[(alpha, method)]
            values.extend([f'{row.loss * 1e4:.4f}', f'{row.violation * 100:.3f}'])
        lines.append(method + ' & ' + ' & '.join(values) + r' \\')
    lines.extend([r'\bottomrule', r'\end{tabular}'])
    texts = {
        'sections_r8/numbers_partial.tex': '% Generated by research/r8_partial_integration/build.py.\n' +
            '\n'.join('\\newcommand{\\' + key + '}{' + value + '}' for key, value in sorted(macros.items())) + '\n',
        'sections_r8/tab_partial.tex': '\n'.join(lines) + '\n',
    }
    for relative, content in texts.items():
        path = destination / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return dict(producer_sha256=sha(__file__), inputs={p: sha(PROJECT / p) for p in INPUTS},
                outputs={p: sha(destination / p) for p in sorted(texts)}, macros=macros)


def verify(manifest):
    assert manifest['producer_sha256'] == sha(__file__)
    for path, wanted in manifest['inputs'].items():
        assert sha(PROJECT / path) == wanted, path
    for path, wanted in manifest['outputs'].items():
        assert sha(SOURCE / path) == wanted, path


def check():
    manifest = json.loads((OUT / 'displays.json').read_text())
    verify(manifest)
    bad = json.loads(json.dumps(manifest))
    bad['outputs'][next(iter(bad['outputs']))] = '0' * 64
    try:
        verify(bad)
    except AssertionError:
        pass
    else:
        raise AssertionError('Corruption negative control failed')
    with tempfile.TemporaryDirectory(prefix='irfa-partial-displays-') as folder:
        assert build(Path(folder)) == manifest
    return dict(exact_display_replay=len(manifest['outputs']), negative_control=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.check:
        print(json.dumps(check()))
    else:
        OUT.mkdir(parents=True, exist_ok=True)
        (OUT / 'displays.json').write_text(json.dumps(build(SOURCE), indent=2) + '\n')
        print('Built two partial-shift displays')
