#!/usr/bin/env python3
"""The two dose-response tables, emitted rather than typed.

Twenty-odd figures would otherwise enter the supplement as literals. They arrive
as generated tables instead, so guard 5 owns them and guard 2 never sees them.

Unit: one row is a grid point, pooled over the 4 assets at 200 dates each.
Aggregation is pool-then-ratio, stated here because a spread computed over
asset-by-leaf cells is a different number.

    python analysis/ml/emit_dose_tables.py
    python analysis/ml/emit_dose_tables.py --controls
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
ALPHA = 0.01
KNOB_THRESHOLD = 1.5      # declared in drafts/prereg_ml.md before the knob arm ran
RED, GRN, YEL = "\033[31m", "\033[32m", "\033[33m"; OFF = "\033[0m"


def leaf_table() -> pd.DataFrame:
    d = pd.read_csv(HERE / "dose_response_raw.csv")
    out = {}
    for est, q in (("LightGBM", "lgbm_q"), ("Quantile forest", "qrf_q")):
        g = d.assign(h=(d["realised"] < d[q]).astype(float))
        out[est] = g.groupby("leaf")["h"].mean()
    t = pd.DataFrame(out)
    t.index.name = "leaf"
    return t


def knob_table() -> pd.DataFrame:
    """Each knob's range INCLUDING the default configuration.

    The object is the range a knob spans, and the default is a point on that
    range -- it just lives in the other arm, because the knob sweep stores only
    the values moved away from it. Reading the swept values alone gives
    max_depth 1.40 instead of 1.60, which is on the other side of the declared
    1.5 threshold, and gives num_leaves 1.00 by accident rather than by
    measurement, since only one value of it was swept. Rule 1: the object is the
    range, not the file.
    """
    k = pd.read_csv(HERE / "knob_sweep_raw.csv")
    g = k.assign(h=(k["realised"] < k["lgbm_q"]).astype(float))
    r = g.groupby(["knob", "value"])["h"].mean().reset_index()
    pi_default = float(leaf_table()["LightGBM"].loc[20])   # library default leaf
    rows = []
    for knob, s in r.groupby("knob"):
        pis = list(s["h"]) + [pi_default]
        lo, hi = min(pis), max(pis)
        rows.append({"knob": knob,
                     "swept": f"{s['value'].min():g}--{s['value'].max():g}",
                     "pi_lo": lo, "pi_hi": hi,
                     "factor": hi / lo if lo > 0 else np.inf})
    return pd.DataFrame(rows).sort_values("factor", ascending=False)


def _tex_leaf(t: pd.DataFrame) -> str:
    L = [r"% Generated by analysis/ml/emit_dose_tables.py -- do not edit by hand.",
         r"\begin{tabular}{@{}lrrrrr@{}}", r"\toprule",
         "Estimator & " + " & ".join(f"${int(i)}$" for i in t.index) + r" \\",
         r"\midrule"]
    for est in t.columns:
        L.append(f"{est} & " + " & ".join(f"${v:.4f}$" for v in t[est]) + r" \\")
    L += [r"\midrule",
          r"$\hat\pi/\alpha$, LightGBM & "
          + " & ".join(f"${v/ALPHA:.1f}$" for v in t["LightGBM"]) + r" \\",
          r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


def _tex_knob(t: pd.DataFrame) -> str:
    esc = {"learning_rate": r"\texttt{learning\_rate}",
           "n_estimators": r"\texttt{n\_estimators}",
           "max_depth": r"\texttt{max\_depth}",
           "num_leaves": r"\texttt{num\_leaves}"}
    L = [r"% Generated by analysis/ml/emit_dose_tables.py -- do not edit by hand.",
         r"\begin{tabular}{@{}lrrrl@{}}", r"\toprule",
         r"Knob & swept from default & $\hat\pi$ range & factor & verdict \\",
         r"\midrule"]
    for _, r in t.iterrows():
        v = "moves the tail" if r["factor"] >= KNOB_THRESHOLD else "does not"
        L.append(f"{esc.get(r['knob'], r['knob'])} & ${r['swept']}$ & "
                 f"${r['pi_lo']:.4f}$--${r['pi_hi']:.4f}$ & "
                 f"${r['factor']:.2f}$ & {v} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


def control_leaf_moves() -> bool:
    """The leaf grid must show a tail that actually moves; a constant column
    would make the exhibit vacuous and would read as 'no dose response'."""
    t = leaf_table()["LightGBM"]
    m = t[t.index >= 5]
    return bool(m.max() / m.min() > 2.0)


def control_knob_threshold_bites() -> bool:
    """The 1.5 threshold must be able to separate. A threshold every knob
    passes, or none passes, carries no information about reading (ii)."""
    t = knob_table()
    return bool((t["factor"] >= KNOB_THRESHOLD).any()
                and (t["factor"] < KNOB_THRESHOLD).any())


def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--controls", action="store_true")
    a = ap.parse_args()
    ok = True
    for name, fn in (("the leaf grid moves the tail", control_leaf_moves),
                     ("the 1.5 knob threshold separates", control_knob_threshold_bites)):
        if fn(): print(f"  {YEL}ctrl{OFF}   {name}")
        else: print(f"  {RED}FAIL{OFF}   control does not fire: {name}"); ok = False
    if not ok: return 2
    if a.controls: return 0
    lt, kt = leaf_table(), knob_table()
    (HERE / "tab_ml_dose.tex").write_text(_tex_leaf(lt))
    (HERE / "tab_ml_knobs.tex").write_text(_tex_knob(kt))
    print(f"\n  {GRN}pass{OFF}   wrote tab_ml_dose.tex ({len(lt)} grid points) "
          f"and tab_ml_knobs.tex ({len(kt)} knobs)")
    print(kt.to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
