#!/usr/bin/env python3
"""Is there measurable violation clustering that the independence test misses?

The degeneracy table shows mean n11 = 0.8 at alpha = 0.01 in Panel A. If the
number of consecutive-violation pairs expected under independence is far below
that, then clustering is present in the data while the standard per-asset test
fails to detect it — a much stronger statement than "the test lacks power".

This checks the arithmetic exactly, on the same n11 definition the pipeline uses
(n11 = #{t : v_t = 1 and v_{t+1} = 1}).

Null used
---------
Condition on the observed number of violations x and place them uniformly at
random among the T test days (random permutation of the violation indicator).
This is the natural "no serial structure, same unconditional rate" null, and it
avoids assuming pi_hat equals alpha. Under it, with
    p2 = x(x-1) / (T(T-1)),  p3 = ...(x-2)/...(T-2),  p4 = ...(x-3)/...(T-3):

    E[n11]   = (T-1) p2 = x(x-1)/T
    Var[n11] = (T-1) p2 (1-p2)
             + 2 (T-2) (p3 - p2^2)                      # overlapping pairs
             + 2 [C(T-1,2) - (T-2)] (p4 - p2^2)         # disjoint pairs

Per-pair z is reported, plus the aggregate. The aggregate z assumes independence
ACROSS assets, which is false — violations cluster on common market days — so it
is reported as an upper bound on significance, not as the test. A properly
pooled statistic needs cross-sectional dependence handling and is left to the
Appendix G extension.

Outputs (analysis/cc_column/):
    n11_excess.csv
    N11_EXCESS.md
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

OUT = Path(__file__).resolve().parent
PANEL_A = {"Moirai-1.1", "Lag-Llama", "GJR-GARCH", "GARCH-N", "Hist-Sim", "EWMA"}


def null_moments(T: int, x: int) -> tuple[float, float]:
    """Exact mean and variance of n11 under a random placement of x violations."""
    if T < 4 or x < 2:
        return (x * (x - 1) / T if T else 0.0), 0.0
    p2 = x * (x - 1) / (T * (T - 1))
    p3 = p2 * (x - 2) / (T - 2)
    p4 = p3 * (x - 3) / (T - 3)
    mean = (T - 1) * p2
    n_pairs = (T - 1) * (T - 2) / 2          # C(T-1, 2)
    var = ((T - 1) * p2 * (1 - p2)
           + 2 * (T - 2) * (p3 - p2 ** 2)
           + 2 * (n_pairs - (T - 2)) * (p4 - p2 ** 2))
    return mean, max(var, 0.0)


def main() -> int:
    src = OUT / "cc_all_variants_alpha001.csv"
    if not src.exists():
        raise SystemExit("run verify_cc_conventions.py first")
    d = pd.read_csv(src)

    # n_test is not stored in that file; recover T from the pipeline.
    import sys
    sys.path.insert(0, str(OUT.parent / "ae_point4"))
    pairs = pd.read_csv(OUT.parent / "ae_point4" / "pairs_long.csv")
    pairs = pairs[pairs["alpha"] == 0.01][["model", "asset", "n_test"]]
    d = d.merge(pairs, on=["model", "asset"], how="left")

    rows = []
    for _, r in d.iterrows():
        T, x, obs = int(r["n_test"]), int(r["n_viol_static"]), int(r["n11_static"])
        mean, var = null_moments(T, x)
        rows.append({
            "model": r["model"], "asset": r["asset"], "panel":
                "A" if r["model"] in PANEL_A else "B",
            "T": T, "x": x, "pi_hat": x / T,
            "n11_obs": obs, "n11_exp": mean, "n11_var": var,
            "z": (obs - mean) / np.sqrt(var) if var > 0 else np.nan,
        })
    e = pd.DataFrame(rows)
    e.to_csv(OUT / "n11_excess.csv", index=False)

    L = ["# Is the clustering real, or is n11 = 0.8 what independence predicts?",
         "", "Generated by `analysis/cc_column/check_n11_excess.py`. Null: the "
         "x observed violations placed uniformly at random among the T test "
         "days, conditioning on the observed rate rather than assuming "
         "pi_hat = alpha.", ""]
    L += ["| Panel | pairs | mean T | mean x | mean n₁₁ observed | "
          "mean n₁₁ expected | ratio | Σobs | Σexp |",
          "|---|---|---|---|---|---|---|---|---|"]
    for panel in ("A", "B", "all"):
        s = e if panel == "all" else e[e["panel"] == panel]
        ratio = s["n11_obs"].sum() / s["n11_exp"].sum()
        L.append(f"| {panel} | {len(s)} | {s['T'].mean():.0f} | "
                 f"{s['x'].mean():.1f} | **{s['n11_obs'].mean():.2f}** | "
                 f"{s['n11_exp'].mean():.2f} | **{ratio:.2f}×** | "
                 f"{int(s['n11_obs'].sum())} | {s['n11_exp'].sum():.1f} |")
    L.append("")

    agg = e.dropna(subset=["z"])
    z_pool = ((agg["n11_obs"] - agg["n11_exp"]).sum()
              / np.sqrt(agg["n11_var"].sum()))
    L += [f"- Pairs with an individually significant excess (z > 1.96): "
          f"**{int((agg['z'] > 1.96).sum())} of {len(agg)}**.",
          f"- Pairs where the independence test was *undefined* yet n₁₁ > 0: "
          f"**{int(((e['n11_obs'] > 0) & (e['n11_obs'] < 1)).sum())}** "
          f"(by construction none — n₁₁ ≥ 1 defines the test), so degeneracy "
          f"means n₁₁ = 0 exactly.",
          f"- Naive pooled z (assumes independence across assets, which is "
          f"false): **{z_pool:.1f}**. Reported as an upper bound on "
          f"significance, not as the test.", ""]

    zero = int((e["n11_obs"] == 0).sum())
    L += [f"- Pairs with n₁₁ = 0: **{zero} of {len(e)}** "
          f"({100 * zero / len(e):.1f}%) — these are exactly the degenerate "
          f"cases; expected n₁₁ under the null averages "
          f"{e['n11_exp'].mean():.2f}, so a zero count is entirely ordinary.",
          ""]
    # Compare the exact test against the LR on the pairs where the LR exists.
    cc = pd.read_csv(OUT / "cc_all_variants_alpha001.csv")
    m = e.merge(cc[["model", "asset", "p_ind_static"]], on=["model", "asset"])
    defined = m[m["p_ind_static"].notna()]
    undef = m[m["p_ind_static"].isna()]
    L += ["## Where the test is defined, it is not blind", "",
          "| | pairs | LR rejects at 5% | exact permutation z > 1.96 |",
          "|---|---|---|---|",
          f"| LR defined (n₁₁ ≥ 1) | {len(defined)} | "
          f"**{int((defined['p_ind_static'] <= 0.05).sum())} "
          f"({100 * (defined['p_ind_static'] <= 0.05).mean():.1f}%)** | "
          f"{int((defined['z'] > 1.96).sum())} "
          f"({100 * (defined['z'] > 1.96).mean():.1f}%) |",
          f"| LR undefined (n₁₁ = 0) | {len(undef)} | — | "
          f"{int((undef['z'] > 1.96).sum())} |", "",
          f"Every one of the {len(undef)} degenerate pairs has n₁₁ = 0 exactly, "
          "so there is genuinely no consecutive-violation evidence in them — "
          "the test is not missing clustering there, there is nothing in that "
          "statistic to miss.", ""]

    L += ["## Verdict", ""]
    ratio_all = e["n11_obs"].sum() / e["n11_exp"].sum()
    rej = 100 * (defined["p_ind_static"] <= 0.05).mean()
    L.append(f"Aggregate clustering is real: {e['n11_obs'].sum():.0f} "
             f"consecutive-violation pairs against {e['n11_exp'].sum():.1f} "
             f"expected under random placement, a factor of "
             f"**{ratio_all:.2f}**.")
    L.append("")
    L.append("**But the tempting headline — \"clustering is present and the "
             "standard test cannot see it\" — is wrong, and the data say "
             "something more damaging.** Where the independence test is "
             f"defined it rejects in **{rej:.0f}%** of pairs. The excess is not "
             "invisible to the test; it was invisible in the *table*, because "
             f"the {len(undef)} pairs with n₁₁ = 0 were counted as passes.")
    L.append("")
    L.append("So the corrected reading is that conditional coverage is **worse** "
             "than the paper reports, not better-than-it-looks. That aligns "
             "with Referee 1's point (viii) rather than answering it, and it "
             "makes the convention fix more urgent, not less.")
    L.append("")
    L.append("The constructive extension survives but changes shape: pooling "
             f"across assets is worth doing for the {len(undef)} pairs where "
             "per-asset evidence is absent by construction, not because the "
             "per-asset test is weak where it applies.")
    L.append("")
    (OUT / "N11_EXCESS.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print((OUT / "N11_EXCESS.md").read_text())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
