#!/usr/bin/env python3
"""What does Table 1's "CC pass" column actually count?

The column would not reproduce from the pipeline's Christoffersen independence
LR: Table 1 reports 24/24 for Moirai-1.1 where the statistic gives 6/24 at
p > 0.05. Since the paper builds a central claim on this column — that 86.1% of
Panel A pairs passing Kupiec also pass Christoffersen, against 40.6% in Panel B,
offered as evidence that the regimes differ in *conditional* coverage — the
definition has to be established before that claim can be restated.

Finding
-------
The column counts a **degenerate test as a pass**. With ~15 violations in ~1500
days, most pairs have no consecutive violations at all (n11 = n10 = 0), the
independence LR is undefined, and the pipeline stores NaN. Counting NaN as a
pass reproduces all ten rows of the published column exactly.

That is arithmetically what the paper reports, but it is not evidence of
independence: it is the absence of any information about independence. This
script separates the two and restates the claim on the informative subset.

Outputs (analysis/cc_column/):
    cc_reproduction.csv   per-model NaN / pass / published counts
    cc_claim.csv          the Panel A vs B claim under each reading
    MEMO.md
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

BASE = Path(__file__).resolve().parent.parent.parent
TABLES = BASE / "cfp_ijf_data" / "paper_outputs" / "tables"
REBUILT = BASE / "analysis" / "moirai11_reconciliation" / \
    "moirai11_full_results_rebuilt.csv"
OUT = Path(__file__).resolve().parent

ALPHA = 0.01
PANEL_A = {"Moirai-1.1", "Lag-Llama", "GJR-GARCH", "GARCH-N", "Hist-Sim", "EWMA"}

# The "CC pass (corrected)" column as printed in tab_master_results.tex.
PUBLISHED = {
    "Moirai-1.1": 24, "Lag-Llama": 24, "GJR-GARCH": 20, "GARCH-N": 18,
    "Hist-Sim": 14, "EWMA": 21, "Chronos-Small": 15, "Chronos-Mini": 16,
    "TimesFM-2.5": 10, "Moirai-2.0": 7,
}


def load() -> pd.DataFrame:
    ar = pd.read_csv(TABLES / "all_results.csv")
    m11 = pd.read_csv(REBUILT)
    d = pd.concat([ar, m11], ignore_index=True)
    d = d[d["alpha"] == ALPHA].copy()
    d["panel"] = np.where(d["model"].isin(PANEL_A), "A", "B")
    d["kup_pass"] = d["p_kup_cp"] > 0.05
    d["cc_degenerate"] = d["p_cc_cp"].isna()
    d["cc_informative_pass"] = d["p_cc_cp"] > 0.05
    d["cc_published_rule"] = d["cc_degenerate"] | d["cc_informative_pass"]
    return d


def main() -> int:
    d = load()

    rows = []
    for model, pub in PUBLISHED.items():
        s = d[d["model"] == model]
        nan = int(s["cc_degenerate"].sum())
        pas = int(s["cc_informative_pass"].sum())
        rows.append({"model": model, "n_degenerate": nan,
                     "n_informative_pass": pas, "sum": nan + pas,
                     "published": pub, "reproduces": (nan + pas) == pub})
    rep = pd.DataFrame(rows)
    rep.to_csv(OUT / "cc_reproduction.csv", index=False)
    n_ok = int(rep["reproduces"].sum())

    claim = []
    for panel in ("A", "B"):
        s = d[(d["panel"] == panel) & d["kup_pass"]]
        inf = s[~s["cc_degenerate"]]
        claim.append({
            "panel": panel, "n_kupiec_pass": len(s),
            "published_rule_pass": int(s["cc_published_rule"].sum()),
            "published_rule_pct": 100 * s["cc_published_rule"].mean(),
            "n_degenerate": int(s["cc_degenerate"].sum()),
            "degenerate_pct": 100 * s["cc_degenerate"].mean(),
            "n_informative": len(inf),
            "informative_pass": int(inf["cc_informative_pass"].sum()),
            "informative_pct": (100 * inf["cc_informative_pass"].mean()
                                if len(inf) else np.nan),
        })
    cl = pd.DataFrame(claim)
    cl.to_csv(OUT / "cc_claim.csv", index=False)
    A, B = cl.iloc[0], cl.iloc[1]

    L = [
        "# Table 1's \"CC pass\" column: what it counts",
        "",
        "Generated by `analysis/cc_column/investigate_cc.py`.",
        "",
        "## The rule",
        "",
        f"**The column counts a degenerate test as a pass**, and that "
        f"reproduces **{n_ok} of 10** published rows exactly.",
        "",
        "| Model | degenerate (NaN) | informative pass (p>0.05) | sum | Table 1 |",
        "|---|---|---|---|---|",
    ]
    for _, r in rep.iterrows():
        L.append(f"| {r['model']} | {r['n_degenerate']} | "
                 f"{r['n_informative_pass']} | **{r['sum']}** | "
                 f"**{r['published']}** |")
    L += [
        "",
        "With roughly 15 violations in ~1500 test days, most pairs have **no "
        "consecutive violations at all** (n11 = n10 = 0). The Christoffersen "
        "independence LR is then undefined, the pipeline stores NaN, and the "
        "table counts it as a pass.",
        "",
        "This is not a coding slip to be silently repaired — it is a convention, "
        "and the published numbers are arithmetically correct under it. But it "
        "is not evidence of independence. It is the absence of any information "
        "about independence.",
        "",
        "## What it does to the paper's claim",
        "",
        "The text states that among Panel A pairs passing Kupiec, 86.1% also "
        "pass Christoffersen, against 40.6% in Panel B, and reads this as "
        "evidence that the regimes differ in conditional coverage.",
        "",
        "| | Panel A | Panel B |",
        "|---|---|---|",
        f"| Pairs passing Kupiec | {A['n_kupiec_pass']} | {B['n_kupiec_pass']} |",
        f"| **Published rule** (NaN = pass) | {A['published_rule_pass']}/"
        f"{A['n_kupiec_pass']} = **{A['published_rule_pct']:.1f}%** | "
        f"{B['published_rule_pass']}/{B['n_kupiec_pass']} = "
        f"**{B['published_rule_pct']:.1f}%** |",
        f"| of which degenerate (no consecutive violations) | "
        f"{A['n_degenerate']}/{A['n_kupiec_pass']} = "
        f"{A['degenerate_pct']:.1f}% | {B['n_degenerate']}/"
        f"{B['n_kupiec_pass']} = {B['degenerate_pct']:.1f}% |",
        f"| **Informative pairs only** | {A['informative_pass']}/"
        f"{A['n_informative']} = **{A['informative_pct']:.1f}%** | "
        f"{B['informative_pass']}/{B['n_informative']} = "
        f"**{B['informative_pct']:.1f}%** |",
        "",
        f"The published percentages reproduce exactly "
        f"({A['published_rule_pct']:.1f}% and {B['published_rule_pct']:.1f}%), "
        f"so the arithmetic is right. But **{A['degenerate_pct']:.0f}% of "
        f"Panel A's \"passes\" carry no information**, and the same is true of "
        f"{B['degenerate_pct']:.0f}% in Panel B.",
        "",
        "## The good news",
        "",
        "**The qualitative finding survives, and in ratio terms it gets "
        "stronger.** Restricted to pairs where the test is actually defined, "
        f"Panel A passes {A['informative_pct']:.1f}% of the time against "
        f"{B['informative_pct']:.1f}% for Panel B — a "
        f"{A['informative_pct'] / B['informative_pct']:.1f}x gap, against "
        f"{A['published_rule_pct'] / B['published_rule_pct']:.1f}x under the "
        "published rule. The regimes do differ in conditional coverage; the "
        "headline percentages were just inflated by the convention.",
        "",
        "## What has to change in the text",
        "",
        "1. Report the informative subset "
        f"({A['informative_pass']}/{A['n_informative']} vs "
        f"{B['informative_pass']}/{B['n_informative']}) as the claim, and the "
        "published-rule numbers only alongside an explicit statement of the "
        "convention.",
        "2. State the convention wherever the CC column appears: a pair with no "
        "consecutive violations is recorded as a pass because the test is "
        "undefined, not because independence was demonstrated.",
        f"3. Report the degeneracy rate itself ({A['degenerate_pct']:.0f}% of "
        f"Panel A, {B['degenerate_pct']:.0f}% of Panel B). It is a substantive "
        "finding: **the Christoffersen independence test has almost no power at "
        "α = 0.01 in samples of this length.** That is the honest answer to "
        "Referee 1's point (viii) and the AE's point 1 — the paper cannot claim "
        "conditional-coverage evidence from this test at the 1% level, and "
        "should say so rather than report a number that looks like evidence.",
        "",
        "Point 3 is worth more to the paper than the original claim was. It "
        "converts a weak result into a measured statement about what the "
        "standard backtest can and cannot detect in the extreme tail — which is "
        "the same identification-constraint argument the paper already makes "
        "for estimation, now extended to testing.",
        "",
    ]
    (OUT / "MEMO.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"CC rule reproduces {n_ok}/10 rows; wrote {OUT}/MEMO.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
