"""Primary-test figure: the static-minus-raw QS contrast on the main panel with its
pointwise intervals across block lengths and its simultaneous bands under the two
reporting families. Reads stored bootstrap summaries only; writes
source/figures/fig_primary_test.{pdf,png,svg} and source/sections_r8/numbers_primary.tex.
--check compares the macro file and the figure inputs."""
import argparse, hashlib, importlib.util, json, os, sys
os.environ.setdefault('MPLCONFIGDIR', '/private/tmp/irfa-r9-mpl')
from pathlib import Path
import numpy as np, pandas as pd
import matplotlib; matplotlib.use('Agg'); import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
ROOT = Path(__file__).resolve().parents[2]
POWER = ROOT / 'artifacts/r8_power_analysis'; REV = ROOT / 'artifacts/r8_referee_revision/results/intervals.csv'
FIG = ROOT / 'source/figures'; OUT = ROOT / 'source/sections_r8'; ART = ROOT / 'artifacts/r9_primary_figure'
sha = lambda p: hashlib.sha256(Path(p).read_bytes()).hexdigest()

def load_plots():
    p = ROOT / 'research/r8_integration/paper_figures.py'; spec = importlib.util.spec_from_file_location('r9_plots', p)
    obj = importlib.util.module_from_spec(spec); spec.loader.exec_module(obj); return obj

def data():
    c = pd.read_csv(POWER / 'contrasts.csv'); s = pd.read_csv(POWER / 'sensitivity.csv'); r = pd.read_csv(REV)
    allp = c[c.contrast == '1_all_pairs'].set_index('block_calendar_days')
    sens = s[(s.contrast == '1_all_pairs') & s.pointwise_lower.notna()].set_index('block_calendar_days')
    eight = r[(r.method == 'Raw') & (r.reference == 'Shift-CP')].set_index('block_calendar_days'); assert (eight.simultaneous_family_size == 8).all()
    point = float(allp.point.iloc[0]); assert np.allclose(allp.point, point) and np.allclose(sens.point, point) and np.allclose(-eight.difference, point, atol=1e-6)
    rows = []
    for b in sorted(set(sens.index) | set(allp.index)):
        src = allp if b in allp.index else sens; row = src.loc[b]
        rows.append(dict(block=int(b), point=point, pointwise_lower=row.pointwise_lower, pointwise_upper=row.pointwise_upper,
                         nine_lower=row.simultaneous_lower if b in allp.index else np.nan, nine_upper=row.simultaneous_upper if b in allp.index else np.nan,
                         one_lower=row.simultaneous_lower if b in sens.index else np.nan, one_upper=row.simultaneous_upper if b in sens.index else np.nan,
                         eight_lower=-eight.loc[b].simultaneous_upper if b in eight.index else np.nan, eight_upper=-eight.loc[b].simultaneous_lower if b in eight.index else np.nan))
    return pd.DataFrame(rows), point

def figure(d, point):
    plots = load_plots(); plots.style(); fig, ax = plt.subplots(figsize=(7, 3.6))
    x = np.arange(len(d)); BLUE, ORANGE, PURPLE, GREY = plots.BLUE, plots.ORANGE, plots.PURPLE, plots.GREY
    ax.axhline(0, color=GREY, lw=.8, ls='--')
    ax.errorbar(x - .18, d.point, yerr=[d.point - d.pointwise_lower, d.pointwise_upper - d.point], fmt='o', color=BLUE, ms=4, capsize=3, lw=1.5, label='Pointwise 95% percentile interval')
    m = d.eight_lower.notna(); ax.errorbar(x[m] + .06, d.point[m], yerr=[d.point[m] - d.eight_lower[m], d.eight_upper[m] - d.point[m]], fmt='s', color=ORANGE, ms=4, capsize=3, lw=1.5, label='Simultaneous 95% band, eight-comparison family')
    m = d.nine_lower.notna(); ax.errorbar(x[m] + .26, d.point[m], yerr=[d.point[m] - d.nine_lower[m], d.nine_upper[m] - d.point[m]], fmt='^', color=PURPLE, ms=4, capsize=3, lw=1.5, label='Simultaneous 95% band, nine-contrast family')
    ax.set_xticks(x, [str(b) for b in d.block]); ax.set_xlabel('Calendar-day block length'); ax.set_ylabel('Static minus raw QS ×10⁴')
    ax.legend(loc='upper left', frameon=False, fontsize=8.5); plots.finish(fig); return fig

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    d, point = data()
    m = {'Point': f'{point:.3f}', 'Blocks': ', '.join(str(b) for b in d.block), 'NBlocks': str(len(d)),
         'PointwiseExcludeCount': str(int((d.pointwise_upper < 0).sum())), 'EightIncludeCount': str(int(((d.eight_lower <= 0) & (d.eight_upper >= 0)).sum())),
         'NineIncludeCount': str(int(((d.nine_lower <= 0) & (d.nine_upper >= 0)).sum())), 'FamilyBlocks': ', '.join(str(b) for b in d.block[d.eight_lower.notna()])}
    for r in d.itertuples():
        tag = {5: 'Five', 10: 'Ten', 20: 'Twenty', 60: 'Sixty', 120: 'OneTwenty'}[r.block]
        m[f'PointLo{tag}'] = f'{r.pointwise_lower:.3f}'; m[f'PointHi{tag}'] = f'{r.pointwise_upper:.3f}'
        if not np.isnan(r.eight_lower): m[f'EightLo{tag}'] = f'{r.eight_lower:.3f}'; m[f'EightHi{tag}'] = f'{r.eight_upper:.3f}'; m[f'NineLo{tag}'] = f'{r.nine_lower:.3f}'; m[f'NineHi{tag}'] = f'{r.nine_upper:.3f}'
    num = '% Generated by research/r9_primary_figure/displays.py; do not edit.\n' + ''.join(f'\\newcommand{{\\nPrim{k}}}{{{v}}}\n' for k, v in m.items())
    inputs = {str(p.relative_to(ROOT)): sha(p) for p in [POWER / 'contrasts.csv', POWER / 'sensitivity.csv', REV]}
    if a.check:
        rec = json.loads((ART / 'displays.json').read_text()); bad = []
        if rec['inputs'] != inputs: bad.append('inputs')
        if (OUT / 'numbers_primary.tex').read_text() != num: bad.append('numbers_primary.tex')
        for ext in ['pdf', 'png', 'svg']:
            if not (FIG / f'fig_primary_test.{ext}').exists(): bad.append(ext)
        print(json.dumps(dict(status='pass' if not bad else 'FAIL', stale=bad))); sys.exit(1 if bad else 0)
    ART.mkdir(parents=True, exist_ok=True); fig = figure(d, point)
    for ext in ['pdf', 'png', 'svg']:
        path = FIG / f'fig_primary_test.{ext}'; kw = {'metadata': {'CreationDate': None, 'ModDate': None}} if ext == 'pdf' else ({'metadata': {'Date': None}} if ext == 'svg' else {})
        with matplotlib.rc_context({'svg.hashsalt': 'r9-primary-test'}): fig.savefig(path, transparent=True, bbox_inches='tight', pad_inches=.06, dpi=210, **kw)
        if ext == 'svg': path.write_text('\n'.join(s.rstrip() for s in path.read_text().splitlines()) + '\n')
    (OUT / 'numbers_primary.tex').write_text(num); d.to_csv(ART / 'figure_data.csv', index=False)
    (ART / 'displays.json').write_text(json.dumps(dict(inputs=inputs, outputs={'numbers_primary.tex': hashlib.sha256(num.encode()).hexdigest(), 'figure_data.csv': sha(ART / 'figure_data.csv')}), indent=2) + '\n'); print('written'); print(d.to_string(index=False))
if __name__ == '__main__': main()
