"""Manuscript displays of the second external test (Developed ex-US 25 portfolios).

Reads artifacts/r8_external2/devexus/results/{summary.csv,intervals.csv,tab_external.tex};
writes source/sections_r8/numbers_extb.tex and tab_external2.tex. --check compares.
"""
import argparse, hashlib, json, sys
from pathlib import Path
import pandas as pd
ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / 'artifacts/r8_external2/devexus/results'; OUT = ROOT / 'source/sections_r8'

def build():
    s = pd.read_csv(RES / 'summary.csv').set_index('method'); iv = pd.read_csv(RES / 'intervals.csv')
    def band(method, ref, block, unit='normalised', scale=1e3):
        r = iv[(iv.method == method) & (iv.reference == ref) & (iv.block_calendar_days == block) & (iv.units == unit)].iloc[0]
        return r.difference * scale, r.simultaneous_lower * scale, r.simultaneous_upper * scale
    m = {}
    m['ExtBPairs'] = str(int(s.loc['Raw', 'pairs']))
    for tag, key in [('Raw', 'Raw'), ('Static', 'Shift-CP'), ('VolErm', 'Vol-ERM'), ('Lone', 'State-L1'), ('PotVol', 'POT-Vol'), ('Pot', 'POT-Shift'), ('Past', 'Past-minimum'), ('Selected', 'Selected-rolling'), ('Gate', 'Loss-gate')]:
        m[tag + 'QS'] = f"{s.loc[key, 'QS_x10000']:.4f}"; m[tag + 'Pi'] = f"{100*s.loc[key, 'violation_rate']:.3f}"
        m[tag + 'Kup'] = str(int(s.loc[key, 'kupiec_rejections'])); m[tag + 'Worse'] = str(int(s.loc[key, 'worse_than_raw']))
    for tag, (meth, ref) in {'StaticRaw': ('Shift-CP', 'Raw'), 'PastSel': ('Past-minimum', 'Selected-rolling'), 'PotVolStatic': ('POT-Vol', 'Shift-CP')}.items():
        for blk, nm in [(20, 'Twenty'), (60, 'Sixty')]:
            d, lo, hi = band(meth, ref, blk); m[f'{tag}{nm}Delta'] = f"{d:.3f}"; m[f'{tag}{nm}Lo'] = f"{lo:.3f}"; m[f'{tag}{nm}Hi'] = f"{hi:.3f}"
    corr = iv[(iv.family == 'correction') & (iv.units == 'normalised')]
    m['CorrExclude'] = str(int(((corr.simultaneous_upper < 0) | (corr.simultaneous_lower > 0)).sum()))
    m = {'ExtB' + k if not k.startswith('ExtB') else k: v for k, v in m.items()}
    num = '% Generated by research/r8_external2/displays.py; do not edit.\n' + ''.join(f'\\newcommand{{\\n{k}}}{{{v}}}\n' for k, v in m.items())
    tab = '% Generated by research/r8_external2/displays.py; do not edit.\n' + (RES / 'tab_external.tex').read_text()
    return num, tab

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    num, tab = build(); targets = {OUT / 'numbers_extb.tex': num, OUT / 'tab_external2.tex': tab}
    if a.check:
        bad = [str(p) for p, t in targets.items() if not p.exists() or p.read_text() != t]
        print(json.dumps(dict(status='pass' if not bad else 'FAIL', stale=bad))); sys.exit(1 if bad else 0)
    for p, t in targets.items(): p.write_text(t)
    rec = dict(inputs={n: hashlib.sha256((RES / n).read_bytes()).hexdigest() for n in ['summary.csv', 'intervals.csv', 'tab_external.tex']},
               outputs={p.name: hashlib.sha256(t.encode()).hexdigest() for p, t in targets.items()})
    (RES / 'displays.json').write_text(json.dumps(rec, indent=2) + '\n'); print('written')
if __name__ == '__main__': main()
