"""Manuscript displays of the nuisance-free optimism-estimator study.

Reads artifacts/r8_optimism_estimator/{summary,oracle_lambda}.csv and admission.json;
writes source/sections_r8/numbers_optest.tex and tab_optest.tex. --check compares.
"""
import argparse, hashlib, json, sys
from pathlib import Path
import pandas as pd
ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / 'artifacts/r8_optimism_estimator'; OUT = ROOT / 'source/sections_r8'
EST = {'E1_blocked_cv': 'Blocked CV', 'E2_block_bootstrap': 'Block bootstrap'}
LAW = {'normal': 'Normal', 't5': '$t_5$'}

def build():
    s = pd.read_csv(ART / 'summary.csv'); adm = json.loads((ART / 'admission.json').read_text())
    orc = pd.read_csv(ART / 'oracle_lambda.csv')
    pos = s[s.bias > 0]; rows = []
    for est in EST:
        for law in LAW:
            for n in [700, 1000, 2000]:
                r = pos[(pos.estimator == est) & (pos.law == law) & (pos.n == n)].iloc[0]
                o = orc[(orc.law == law) & (orc.n == n) & (orc.bias > 0)].iloc[0]
                rows.append(f"{EST[est]} & {LAW[law]} & {n} & {r.ratio_to_2A0:.3f} & [{r.band_lower:.3f}, {r.band_upper:.3f}] & {r.mean_lambda_hat:.2f} & {o.lambda_star:.2f} & {1e4*r.shrunk_minus_full:.4f} \\\\")
    tab = ('% Generated by research/r8_optimism_estimator/displays.py; do not edit.\n'
           '\\begin{tabular}{llrrrrrr}\n\\toprule\nEstimator & Law & $n$ & $\\hat O/(2A_{0,n})$ & Band & $\\bar{\\hat\\lambda}$ & $\\lambda_*$ & Shrunk $-$ full \\\\\n\\midrule\n'
           + '\n'.join(rows) + '\n\\bottomrule\n\\end{tabular}\n')
    # criterion-2 counts for b>0, n>=700 per estimator
    c2 = {}
    for est in EST:
        sub = pos[(pos.estimator == est) & (pos.n >= 700)]
        c2[est] = dict(cells=int(len(sub)), worse=int((sub.shrunk_minus_full > 0).sum()))
    ex = pos[(pos.estimator == 'E1_blocked_cv') & (pos.law == 'normal') & (pos.n == 1000)].iloc[0]
    ex2 = pos[(pos.estimator == 'E2_block_bootstrap') & (pos.law == 'normal') & (pos.n == 1000)].iloc[0]
    oex = orc[(orc.law == 'normal') & (orc.n == 1000) & (orc.bias > 0)].iloc[0]
    acc = {est: adm['estimators'][est]['criterion_1_penalty_accuracy'] for est in EST}
    maxerr = {est: max(c['abs_error_bias0'] for c in acc[est]['cells'] if c['applies']) for est in EST}
    mac = dict(OptEstCvMaxErr=f"{100*maxerr['E1_blocked_cv']:.1f}", OptEstBootMaxErr=f"{100*maxerr['E2_block_bootstrap']:.1f}",
               OptEstCells=str(c2['E1_blocked_cv']['cells']), OptEstCvWorse=str(c2['E1_blocked_cv']['worse']), OptEstBootWorse=str(c2['E2_block_bootstrap']['worse']),
               OptEstExFull=f"{1e4*ex.loss_full:.3f}", OptEstExShrunkCv=f"{1e4*ex.loss_shrunk:.3f}", OptEstExShrunkBoot=f"{1e4*ex2.loss_shrunk:.3f}",
               OptEstExLambdaCv=f"{ex.mean_lambda_hat:.2f}", OptEstExLambdaBoot=f"{ex2.mean_lambda_hat:.2f}", OptEstExLambdaStar=f"{oex.lambda_star:.2f}",
               OptEstExLambdaSd=f"{ex.sd_lambda_hat:.2f}", OptEstOracleGain=f"{1e4*oex.oracle_minus_full:.3f}", OptEstHistories='500', OptEstBoot='200')
    num = '% Generated by research/r8_optimism_estimator/displays.py; do not edit.\n' + ''.join(f'\\newcommand{{\\n{k}}}{{{v}}}\n' for k, v in mac.items())
    return num, tab

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    num, tab = build(); targets = {OUT / 'numbers_optest.tex': num, OUT / 'tab_optest.tex': tab}
    if a.check:
        bad = [str(p) for p, t in targets.items() if not p.exists() or p.read_text() != t]
        print(json.dumps(dict(status='pass' if not bad else 'FAIL', stale=bad))); sys.exit(1 if bad else 0)
    for p, t in targets.items(): p.write_text(t)
    rec = dict(inputs={n: hashlib.sha256((ART / n).read_bytes()).hexdigest() for n in ['summary.csv', 'oracle_lambda.csv', 'admission.json']},
               outputs={p.name: hashlib.sha256(t.encode()).hexdigest() for p, t in targets.items()})
    (ART / 'displays.json').write_text(json.dumps(rec, indent=2) + '\n'); print('written')
if __name__ == '__main__': main()
