"""Manuscript displays of the common-window study.

Reads artifacts/r8_common_window/{contrast,split_dates}.csv and run.json; writes source/sections_r8/{numbers_common,tab_common,tab_split_dates}.tex. --check compares.
"""
import argparse, hashlib, json, sys
from pathlib import Path
import pandas as pd
ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / 'artifacts/r8_common_window'; OUT = ROOT / 'source/sections_r8'

def build():
    c = pd.read_csv(ART / 'contrast.csv').set_index('block_calendar_days'); s = pd.read_csv(ART / 'split_dates.csv'); run = json.loads((ART / 'run.json').read_text())['summary']
    m = {'Start': pd.Timestamp(run['common_start']).strftime('%-d %B %Y'), 'End': pd.Timestamp(run['common_end']).strftime('%-d %B %Y'),
         'Days': f"{run['trading_dates']:,}", 'PairDays': f"{run['pair_days']:,}", 'MinObs': str(run['min_n_common']), 'MaxObs': str(run['max_n_common']),
         'MinPairs': str(run['min_pairs_present']), 'Point': f"{run['point_x1e4']:.3f}", 'FullPoint': f"{run['full_window_point_x1e4']:.3f}",
         'RawQS': f"{run['raw_QS_x1e4']:.4f}", 'StaticQS': f"{run['static_QS_x1e4']:.4f}", 'RollingQS': f"{run['rolling_QS_x1e4']:.4f}",
         'RawPi': f"{run['raw_pi_pct']:.3f}", 'StaticPi': f"{run['static_pi_pct']:.3f}", 'RollingPi': f"{run['rolling_pi_pct']:.3f}", 'Improved': str(run['pairs_improved'])}
    for blk, nm in [(20, 'Twenty'), (60, 'Sixty')]:
        r = c.loc[blk]
        m[f'Sd{nm}'] = f"{r.bootstrap_sd_x1e4:.3f}"; m[f'PointLo{nm}'] = f"{r.pointwise_lower_x1e4:.3f}"; m[f'PointHi{nm}'] = f"{r.pointwise_upper_x1e4:.3f}"
        m[f'StudLo{nm}'] = f"{r.studentised_lower_x1e4:.3f}"; m[f'StudHi{nm}'] = f"{r.studentised_upper_x1e4:.3f}"; m[f'Crit{nm}'] = f"{r.studentised_critical_value:.3f}"
    m['EarliestStart'] = pd.Timestamp(s.test_start.min()).strftime('%-d %B %Y'); m['LatestStart'] = pd.Timestamp(s.test_start.max()).strftime('%-d %B %Y')
    m['EarliestAsset'] = s.sort_values('test_start').asset.iloc[0]; m['LatestAsset'] = s.sort_values('test_start').asset.iloc[-1]
    m['MinTest'] = str(int(s.n_test.min())); m['MaxTest'] = str(int(s.n_test.max()))
    num = '% Generated by research/r8_common_window/displays.py; do not edit.\n' + ''.join(f'\\newcommand{{\\nCommon{k}}}{{{v}}}\n' for k, v in m.items())
    rows = [f"{int(b)} & {r.point_x1e4:.3f} & {r.bootstrap_sd_x1e4:.3f} & [{r.pointwise_lower_x1e4:.3f}, {r.pointwise_upper_x1e4:.3f}] & [{r.studentised_lower_x1e4:.3f}, {r.studentised_upper_x1e4:.3f}] \\\\" for b, r in c.iterrows()]
    tab = ('% Generated by research/r8_common_window/displays.py; do not edit.\n\\begin{tabular}{lrrrr}\n\\toprule\n'
           'Block (days) & Mean & Bootstrap SD & Percentile 95\\% & Studentised 95\\% \\\\\n\\midrule\n' + '\n'.join(rows) + '\n\\bottomrule\n\\end{tabular}\n')
    srows = [f"{r.asset} & {r.first_date} & {r.test_start} & {r.last_date} & {int(r.n_calibration):,} & {int(r.n_test):,} \\\\" for r in s.itertuples()]
    split = ('% Generated by research/r8_common_window/displays.py; do not edit.\n\\begin{tabular}{llllrr}\n\\toprule\n'
             'Series & First date & Test start & Last date & $n_{\\mathrm{cal}}$ & $n_{\\mathrm{test}}$ \\\\\n\\midrule\n' + '\n'.join(srows) + '\n\\bottomrule\n\\end{tabular}\n')
    return num, tab, split

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    num, tab, split = build(); targets = {OUT / 'numbers_common.tex': num, OUT / 'tab_common.tex': tab, OUT / 'tab_split_dates.tex': split}
    if a.check:
        bad = [str(p) for p, t in targets.items() if not p.exists() or p.read_text() != t]
        print(json.dumps(dict(status='pass' if not bad else 'FAIL', stale=bad))); sys.exit(1 if bad else 0)
    for p, t in targets.items(): p.write_text(t)
    rec = dict(inputs={n: hashlib.sha256((ART / n).read_bytes()).hexdigest() for n in ['contrast.csv', 'split_dates.csv', 'run.json']},
               outputs={p.name: hashlib.sha256(t.encode()).hexdigest() for p, t in targets.items()})
    (ART / 'displays.json').write_text(json.dumps(rec, indent=2) + '\n'); print('written')
if __name__ == '__main__': main()
