"""Two deterministic displays from the fully replayed regime study."""
import argparse
import hashlib
import json
from pathlib import Path
import tempfile
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
ART = ROOT/'artifacts/r8_regime'
SOURCE = ROOT/'source'


def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def build(dest):
    validation = json.loads((ART/'validation.json').read_text())
    assert validation['fresh_replay_blocks'] == 10 and validation['regenerated_innovation_paths'] == 1000
    aggregation = json.loads((ART/'aggregation.json').read_text())
    for name in ('summary.csv', 'decisions.csv'):
        assert sha(ART/'results'/name) == aggregation['outputs']['results/'+name]
    s = pd.read_csv(ART/'results/summary.csv')
    d = pd.read_csv(ART/'results/decisions.csv')
    def cell(kind, alpha, scenario, period, method):
        g = s[(s.innovation == kind)&(s.alpha == alpha)&(s.scenario == scenario)&(s.period == period)&(s.method == method)]
        assert len(g) == 1
        return g.iloc[0]
    macros = {}
    for period, label in [('acute', 'Acute'), ('post', 'Post')]:
        row = cell('t5', .01, 'jump_ewma', period, 'Rolling250')
        for suffix, value in [('Delta', row.difference_vs_Raw*1e4), ('SE', row.MCSE_vs_Raw*1e4)]:
            macros['nRegime'+label+suffix] = f'{value:.3f}'
    for method, label in [('Raw', 'Raw'), ('InitialKupiecGate', 'Gate')]:
        row = cell('t5', .01, 'appears', 'post', method)
        macros['nRegimeAppears'+label+'Pi'] = f'{100*row.hit_probability:.2f}'
        macros['nRegimeAppears'+label+'QS'] = f'{1e4*row.risk:.3f}'
    rate = d[(d.innovation == 't5')&(d.alpha == .01)&(d.scenario == 'appears')].apply_gate.mean()
    macros['nRegimeGateApplyPct'] = f'{100*rate:.1f}'
    target = dest/'sections_r8'
    target.mkdir(parents=True, exist_ok=True)
    numbers = target/'numbers_regime.tex'
    numbers.write_text('% Generated by research/r8_regime/build_paper.py.\n'+
        '\n'.join('\\newcommand{\\'+key+'}{'+value+'}' for key, value in sorted(macros.items()))+'\n')
    table = [r'\begin{tabular}{llrrrr}', r'\toprule',
             r'Law & Tail & $\Delta$QS, days 1--20 & MCSE & $\Delta$QS, days 1--1,000 & MCSE \\', r'\midrule']
    for kind, label in [('normal', 'Normal'), ('t5', 'Student-$t(5)$')]:
        for alpha in (.01, .05):
            a = cell(kind, alpha, 'jump_ewma', 'acute', 'Rolling250')
            b = cell(kind, alpha, 'jump_ewma', 'post', 'Rolling250')
            table.append(f'{label} & {100*alpha:.0f}'+r'\%'+f' & {a.difference_vs_Raw*1e4:.3f} & {a.MCSE_vs_Raw*1e4:.3f} & {b.difference_vs_Raw*1e4:.3f} & {b.MCSE_vs_Raw*1e4:.3f}'+r' \\')
    table += [r'\bottomrule', r'\end{tabular}']
    tab = target/'tab_regime.tex'
    tab.write_text('\n'.join(table)+'\n')
    return {'producer_sha256': sha(__file__),
            'inputs': {str(p.relative_to(ROOT)): sha(p) for p in [ART/'validation.json', ART/'aggregation.json', ART/'results/summary.csv', ART/'results/decisions.csv']},
            'outputs': {str(p.relative_to(dest)): sha(p) for p in (numbers, tab)}}


def verify(record):
    assert record['producer_sha256'] == sha(__file__)
    for p, h in record['inputs'].items():
        assert sha(ROOT/p) == h
    for p, h in record['outputs'].items():
        assert sha(SOURCE/p) == h


def check():
    record = json.loads((ART/'paper_displays.json').read_text())
    verify(record)
    bad = json.loads(json.dumps(record))
    bad['outputs'][next(iter(bad['outputs']))] = '0'*64
    try:
        verify(bad)
    except AssertionError:
        pass
    else:
        raise AssertionError('Display corruption negative control failed')
    with tempfile.TemporaryDirectory(prefix='irfa-regime-displays-') as temp:
        assert build(Path(temp)) == record
    return {'exact_display_replay': 2, 'corruption_negative_control': True}


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    if args.check:
        print(json.dumps(check()))
    else:
        record = build(SOURCE)
        (ART/'paper_displays.json').write_text(json.dumps(record, indent=2)+'\n')
        print('Built two regime-study displays.')
