"""Deterministic presentation changes to archived results; no statistical refitting.

The original table outputs are retained byte-for-byte for public replay.
This formatter adds the existing projected-DtACI row and disambiguates the
coefficient-count symbol. INPUTS.json binds the four unchanged source files.
"""
import argparse
import csv
import hashlib
import json
from pathlib import Path

SOURCE = Path(__file__).resolve().parents[1]
EDITORIAL = SOURCE / 'editorial'


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verify_inputs(manifest):
    for name, expected in manifest.items():
        if digest(SOURCE / name) != expected:
            raise ValueError(f'Input hash mismatch: {name}')


def render():
    manifest = json.loads((EDITORIAL / 'INPUTS.json').read_text())['inputs']
    verify_inputs(manifest)
    with (EDITORIAL / 'summary.csv').open(newline='') as stream:
        summary = list(csv.DictReader(stream))
    with (EDITORIAL / 'intervals.csv').open(newline='') as stream:
        intervals = list(csv.DictReader(stream))
    method = 'DtACI-projected-expected'
    rows = [r for r in summary if r['method'] == method]
    bands = [r for r in intervals if r['method'] == method
             and r['reference'] == 'Shift-CP' and r['block_calendar_days'] == '60']
    assert len(rows) == len(bands) == 1
    r, b = rows[0], bands[0]
    assert int(r['pairs']) == 240 and int(r['kupiec_available']) == 0
    assert float(b['simultaneous_family_size']) == 8
    point = f"$[{float(b['lower']):.4f}, {float(b['upper']):.4f}]$"
    band = f"$[{float(b['simultaneous_lower']):.4f}, {float(b['simultaneous_upper']):.4f}]$"
    row = (f"Projected DtACI & {float(r['QS_x10000']):.4f} & "
           f"{100 * float(r['violation_rate']):.3f} & -- & "
           f"{int(r['worse_than_raw'])} & {point} & {band}" + r' \\' + '\n')
    original = (SOURCE / 'sections_r8/tab_ten_strong.tex').read_text()
    assert 'DtACI' not in original and original.count('Rolling 500 &') == 1
    complete = original.replace('Rolling 500 &', row + 'Rolling 500 &')
    assert complete.replace(row, '') == original
    controlled = (SOURCE / 'sections_r8/tab_controlled_full.tex').read_text()
    assert controlled.count('Correction & $p$ &') == 1
    dimensions = controlled.replace('Correction & $p$ &', 'Correction & $d$ &')
    assert dimensions.replace('Correction & $d$ &', 'Correction & $p$ &') == controlled
    header = '% Generated by editorial/render_tables.py from tab_controlled_full.tex; do not edit.\n'
    assert dimensions.startswith('% Generated by build_paper_outputs.py; do not edit.\n')
    dimensions = header + dimensions.split('\n', 1)[1]
    complete = '% Generated by editorial/render_tables.py from tab_ten_strong.tex; do not edit.\n' + complete
    return {'sections_r8/tab_ten_strong_complete.tex': complete,
            'sections_r8/tab_controlled_dimensions.tex': dimensions}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    outputs = render()
    if args.check:
        for name, expected in outputs.items():
            assert (SOURCE / name).read_text() == expected, name
        # Verify that a corrupted provenance claim is rejected.
        invalid = json.loads((EDITORIAL / 'INPUTS.json').read_text())['inputs']
        invalid[next(iter(invalid))] = '0' * 64
        try:
            verify_inputs(invalid)
        except ValueError:
            pass
        else:
            raise AssertionError('Input corruption was not detected')
        print(json.dumps({'exact_outputs': len(outputs), 'negative_control': True}))
    else:
        for name, value in outputs.items():
            (SOURCE / name).write_text(value)
        print(json.dumps({'written': list(outputs)}))


if __name__ == '__main__':
    main()
