"""Deterministic paper displays from completed, validated research outputs.

No fitting, simulation or selection. --check rebuilds to a temporary directory
and compares every byte, with a deliberate output-corruption negative control.
"""
import argparse
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import sys
import tempfile
os.environ.setdefault('MPLCONFIGDIR', '/private/tmp/irfa-integration-mpl')
os.environ.setdefault('XDG_CACHE_HOME', '/private/tmp/irfa-integration-cache')
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.figure import Figure

ROOT = Path(__file__).resolve().parents[2]
DEST = ROOT/'source'
ART = ROOT/'artifacts/r8_commodity_etp/panel/risk_displays'
INPUTS = [f'artifacts/r8_commodity_etp/panel/decision/{n}.csv' for n in
          ['summary','intervals','sensitivity_intervals','pairs','decisions']]
INPUTS += [f'artifacts/r8_mechanism/results/{n}.csv' for n in ['summary','paired','counts']]
INPUTS += ['research/r8_integration/paper_figures.py']


def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def load(name, path):
    spec=importlib.util.spec_from_file_location(name, path)
    mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod)
    return mod


def build(dest):
    out=dest/'sections_r8';figdir=dest/'figures'
    out.mkdir(parents=True,exist_ok=True);figdir.mkdir(parents=True,exist_ok=True)
    written=[]
    def write(name, text):
        p=out/name;p.write_text(text+'\n');written.append(p)
    d=pd.read_csv(ROOT/INPUTS[0]).set_index('method')
    intervals=pd.read_csv(ROOT/INPUTS[1])
    sens=pd.read_csv(ROOT/INPUTS[2])
    pairs=pd.read_csv(ROOT/INPUTS[3])
    s=pd.read_csv(ROOT/'artifacts/r8_mechanism/results/summary.csv')
    macros={}
    def macro(name,val,places=4): macros['nRisk'+name]=f'{val:.{places}f}'
    for name,key in [('Pot','POT-Shift'),('PotVol','POT-Vol'),('Lone','State-L1'),
                     ('Dtaci','DtACI-projected-expected'),('Gate','Loss-gate'),('Past','Past-minimum')]:
        macro(name+'QS',d.loc[key,'QS_x10000'])
    macro('GatePi',100*d.loc['Loss-gate','violation_rate'],3)
    macro('GateKup',d.loc['Loss-gate','kupiec_rejections'],0)
    macro('GateWorse',d.loc['Loss-gate','worse_than_raw'],0)
    dec=pd.read_csv(ROOT/INPUTS[4])
    macro('GateRaw',(dec.gate_selected=='Raw').sum(),0)
    macro('GateApply',(dec.gate_selected!='Raw').sum(),0)
    w=pairs.pivot(index=['model','asset'],columns='method',values='QS')
    diff=w['POT-Shift']-w['Shift-CP']
    macro('CryptoShare',100*diff[diff.index.get_level_values('asset').isin(['BTC','ETH'])].sum()/diff.sum(),1)
    for b in [20,60]:
        a=intervals[(intervals.method=='POT-Shift')&(intervals.reference=='Shift-CP')&(intervals.block_calendar_days==b)].iloc[0]
        for col,suffix in [('difference','Delta'),('simultaneous_lower','Lo'),('simultaneous_upper','Hi')]:
            macro('Pot'+{20:'Twenty',60:'Sixty'}[b]+suffix,a[col])
    a=sens[(sens.method=='POT-Shift')&(sens.sensitivity=='without_crypto')&(sens.block_calendar_days==60)].iloc[0]
    for col,suffix in [('difference','Delta'),('simultaneous_lower','Lo'),('simultaneous_upper','Hi')]:macro('ExCrypto'+suffix,a[col])
    for phi,tag in [(0,'Iid'),(.8,'Dep')]:
        a=s[(s.module=='ar')&(s.innovation=='normal')&(s.alpha==.01)&(s.truth=='constant')&(s.n_cal==250)&(s.phi==phi)]
        for method,mname in [('Shift-CP','Cp'),('POT80-Shift','Pot')]:macro('Ar'+tag+mname,a[a.method==method].iloc[0].difference_vs_Raw*10000)
    g=s[(s.module=='garch')&(s.innovation=='t5')&(s.alpha==.01)&(s.truth=='constant')&(s.n_cal==125)].set_index('method')
    for m,tag in [('State-L1','Lone'),('State-L1-clipped','Clip'),('POT80-Shift','Pot')]:macro('Short'+tag,g.loc[m,'mean_expected_QS']*10000,2)
    macro('ShortLoneMedian',g.loc['State-L1','median_expected_QS']*10000,2)
    macro('ShortTopFive',g.loc['State-L1','top_five_share_of_total_regret']*100,1)
    write('numbers_risk.tex','% Generated by research/r8_integration/build.py.\n'+'\n'.join('\\newcommand{\\'+k+'}{'+v+'}' for k,v in sorted(macros.items())))
    methods=[('Raw','Raw'),('Shift-CP','Shift-CP'),('Vol-ERM','Vol-ERM'),('State-L1','Regularised state'),
             ('POT-Shift','POT-Shift'),('POT-Vol','POT-Vol'),('DtACI-projected-expected','Projected DtACI'),
             ('Rolling500','Rolling 500'),('Loss-gate','Loss gate'),('Past-minimum','Past-loss minimum')]
    lines=[r'\begin{tabular}{lrrrr}',r'\toprule',r'Method & QS & Viol. (\%) & UC & Worse than raw \\',r'\midrule']
    for method,label in methods:
        r=d.loc[method];uc=str(int(r.kupiec_rejections)) if r.kupiec_available else '--'
        lines.append(f'{label} & {r.QS_x10000:.4f} & {100*r.violation_rate:.3f} & {uc} & {int(r.worse_than_raw)}'+r' \\')
    lines += [r'\bottomrule',r'\end{tabular}'];write('tab_strong.tex','\n'.join(lines))
    plots=load('risk_paper_plots',ROOT/'research/r8_integration/paper_figures.py')
    figures=[('fig_dependence_cost',plots.dependence(s)),
             ('fig_mechanism_one',plots.complexity(s,.01)),
             ('fig_mechanism_five',plots.complexity(s,.05)),
             ('fig_strong_frontier',plots.frontier(d,intervals,sens))]
    for name,fig in figures:
        for ext in ['pdf','png','svg']:
            p=figdir/f'{name}.{ext}'
            kw={'metadata':{'CreationDate':None,'ModDate':None}} if ext=='pdf' else ({'metadata':{'Date':None}} if ext=='svg' else {})
            with matplotlib.rc_context({'svg.hashsalt':'irfa-r8-risk'}):
                fig.savefig(p,transparent=True,bbox_inches='tight',pad_inches=.06,dpi=210,**kw)
            if ext == 'svg':
                p.write_text('\n'.join(line.rstrip() for line in p.read_text().splitlines()) + '\n')
            written.append(p)
        plt.close(fig)
    return {'producer_sha256':sha(__file__),'inputs':{p:sha(ROOT/p) for p in INPUTS},
            'outputs':{str(p.relative_to(dest)):sha(p) for p in sorted(written)},'macros':macros}


def verify(manifest):
    assert manifest['producer_sha256']==sha(__file__),'producer changed'
    for p,h in manifest['inputs'].items():assert sha(ROOT/p)==h,('input changed',p)
    for p,h in manifest['outputs'].items():assert sha(DEST/p)==h,('display changed',p)


def check():
    m=json.loads((ART/'displays.json').read_text());verify(m)
    bad=json.loads(json.dumps(m));bad['outputs'][next(iter(bad['outputs']))]='0'*64
    try:verify(bad)
    except AssertionError:pass
    else:raise AssertionError('Corruption negative control failed')
    with tempfile.TemporaryDirectory(prefix='irfa-risk-replay-') as folder:
        new=build(Path(folder));assert new==m,'display replay differs'
    return {'exact_display_replay':len(m['outputs']),'negative_control':True}


if __name__=='__main__':
    ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');a=ap.parse_args()
    if a.check:print(json.dumps(check()))
    else:
        m=build(DEST);ART.mkdir(exist_ok=True);(ART/'displays.json').write_text(json.dumps(m,indent=2)+'\n')
        print('Built',len(m['outputs']),'displays')
