"""Manuscript displays of the 97.5% ES and capital-component study.

Reads artifacts/r9_es975/{summary.csv, run.json}; writes source/sections_r8/{numbers_es975,tab_es975}.tex. --check compares.
"""
import argparse, hashlib, json, sys
from pathlib import Path
import pandas as pd
ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / 'artifacts/r9_es975'; OUT = ROOT / 'source/sections_r8'
ROWS = [('Moirai-1.1', 'Moirai', 'Moirai-1.1'), ('Lag-Llama', 'Lag', 'Lag-Llama'), ('GJR-GARCH', 'GjrN', 'GJR-N'), ('GJR-GARCH-t', 'GjrT', 'GJR-$t$'),
        ('GARCH-N', 'GarchN', 'GARCH-N'), ('Hist-Sim', 'Hs', 'HS'), ('EWMA', 'Ewma', 'EWMA')]

def build():
    s = pd.read_csv(ART / 'summary.csv').set_index('model'); run = json.loads((ART / 'run.json').read_text())['summary']
    m = {'Pairs': str(run['pairs']), 'EsDraws': str(run['es_draws']), 'EsWindowPoints': str(run['es_window_points']),
         'RawES': f"{100 * run['ES975_raw_pair_equal']:.3f}", 'StaticES': f"{100 * run['ES975_static_pair_equal']:.3f}",
         'EsRatioPct': f"{100 * (run['ES_ratio_pair_equal'] - 1):.1f}", 'VarRatioPct': f"{100 * (run['VaR1_ratio_pair_equal'] - 1):.1f}",
         'CompRaw': f"{100 * run['component_raw']:.3f}", 'CompStatic': f"{100 * run['component_static']:.3f}", 'CompRatioPct': f"{100 * (run['component_ratio'] - 1):.1f}",
         'CompRawHi': f"{100 * run['component_raw_hi']:.3f}", 'CompStaticHi': f"{100 * run['component_static_hi']:.3f}", 'CompRatioHiPct': f"{100 * (run['component_ratio_hi'] - 1):.1f}",
         'PairsFall': str(run['pairs_component_falls']), 'PairsFallHi': str(run['pairs_component_falls_hi'])}
    for zone in ['Green', 'Yellow', 'Red']:
        m[f'ZonesRaw{zone}'] = str(run['zones_raw'].get(zone, 0)); m[f'ZonesStatic{zone}'] = str(run['zones_static'].get(zone, 0))
    lines = [r'\begingroup\setlength{\tabcolsep}{3pt}', r'\begin{tabular}{lrrrrrrr}', r'\toprule',
             r'Forecaster & ES raw & ES static & ES ratio & Comp.\ raw & Comp.\ static & Comp.\ ratio & Falls \\', r'\midrule']
    for model, tag, label in ROWS:
        r = s.loc[model]
        for k, v in [('RawES', 100 * r.ES975_raw), ('StaticES', 100 * r.ES975_static), ('EsRatio', r.ES_ratio), ('CompRaw', 100 * r.component_raw), ('CompStatic', 100 * r.component_static), ('CompRatio', r.component_ratio)]:
            m[tag + k] = f'{v:.3f}'
        m[tag + 'Falls'] = str(int(r.pairs_component_falls))
        lines.append(f'{label} & {100 * r.ES975_raw:.3f} & {100 * r.ES975_static:.3f} & {r.ES_ratio:.3f} & {100 * r.component_raw:.3f} & {100 * r.component_static:.3f} & {r.component_ratio:.3f} & {int(r.pairs_component_falls)} \\\\')
    lines += [r'\midrule', f"All pairs & {m['RawES']} & {m['StaticES']} & {run['ES_ratio_pair_equal']:.3f} & {m['CompRaw']} & {m['CompStatic']} & {run['component_ratio']:.3f} & {m['PairsFall']} \\\\", r'\bottomrule', r'\end{tabular}', r'\endgroup']
    m = {k: ('0.0' if v == '-0.0' else v) for k, v in m.items()}  # no negative zero in prose
    head = '% Generated by research/r9_es975/displays.py; do not edit.\n'
    return head + ''.join(f'\\newcommand{{\\nEsB{k}}}{{{v}}}\n' for k, v in m.items()), head + '\n'.join(lines) + '\n'

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    num, tab = build(); targets = {OUT / 'numbers_es975.tex': num, OUT / 'tab_es975.tex': tab}
    if a.check:
        bad = [str(p) for p, t in targets.items() if not p.exists() or p.read_text() != t]
        print(json.dumps(dict(status='pass' if not bad else 'FAIL', stale=bad))); sys.exit(1 if bad else 0)
    for p, t in targets.items(): p.write_text(t)
    rec = dict(inputs={n: hashlib.sha256((ART / n).read_bytes()).hexdigest() for n in ['summary.csv', 'run.json']}, outputs={p.name: hashlib.sha256(t.encode()).hexdigest() for p, t in targets.items()})
    (ART / 'displays.json').write_text(json.dumps(rec, indent=2) + '\n'); print('written')
if __name__ == '__main__': main()
