"""Manuscript displays of the binomial traffic-light study.

Reads artifacts/r8_basel_binomial/{zone_counts,ceilings}.csv; writes
source/sections_r8/numbers_basel.tex and tab_basel.tex. --check compares.
"""
import argparse, hashlib, json, sys
from pathlib import Path
import pandas as pd
ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / 'artifacts/r8_basel_binomial'; OUT = ROOT / 'source/sections_r8'
LABELS = {'Shift-CP': 'Shift-CP', 'Rolling250': 'Rolling 250', 'Rolling500': 'Rolling 500', 'Selected-rolling': 'Selected rolling',
          'Gate-selected-rolling': 'Coverage-gated rolling', 'Loss-gate': 'Loss gate', 'Past-minimum': 'Past-loss minimum',
          'State-L1': 'Regularised state'}
TABLE = ['Raw', 'Shift-CP', 'Shift-ERM', 'Vol-ERM', 'State-L1', 'POT-Shift', 'POT-Vol', 'Rolling250', 'Rolling500',
         'Selected-rolling', 'Gate-selected-rolling', 'Loss-gate', 'Past-minimum']
TAGS = {'Raw': 'Raw', 'Shift-CP': 'Static', 'Rolling250': 'Rolling', 'Loss-gate': 'Gate', 'Selected-rolling': 'Selected'}

def build():
    c = pd.read_csv(ART / 'zone_counts.csv').set_index('method'); ce = pd.read_csv(ART / 'ceilings.csv')
    mac = {}
    for method, tag in TAGS.items():
        for rule, rn in [('scaled', 'Scaled'), ('binomial', 'Bin')]:
            for zone in ['Green', 'Yellow', 'Red']:
                mac[f'{tag}{zone}{rn}'] = str(int(c.loc[method, f'{rule}_{zone}']))
    mac['Pairs'] = str(int(c.loc['Raw', 'pairs']))
    mac['Windows'] = str(len(ce))
    mac['GreenCeilMin'] = f"{100*ce.green_ceiling_rate.min():.2f}"; mac['GreenCeilMax'] = f"{100*ce.green_ceiling_rate.max():.2f}"
    mac['RedBoundMin'] = f"{100*ce.red_boundary_rate.min():.2f}"; mac['RedBoundMax'] = f"{100*ce.red_boundary_rate.max():.2f}"
    mac['ScaledRedBound'] = f"{100*9/250:.1f}"
    longest = ce.sort_values('n_test').iloc[-1]; shortest = ce.sort_values('n_test').iloc[0]
    mac['LongestN'] = str(int(longest.n_test)); mac['LongestYellow'] = str(int(longest.yellow_from)); mac['LongestRed'] = str(int(longest.red_from))
    mac['ShortestN'] = str(int(shortest.n_test)); mac['ShortestYellow'] = str(int(shortest.yellow_from)); mac['ShortestRed'] = str(int(shortest.red_from))
    mac['RawMovedDown'] = str(int(c.loc['Raw', 'moved_down'])); mac['StaticMovedDown'] = str(int(c.loc['Shift-CP', 'moved_down']))
    num = '% Generated by research/r8_basel_binomial/displays.py; do not edit.\n' + ''.join(f'\\newcommand{{\\nBasel{k}}}{{{v}}}\n' for k, v in mac.items())
    rows = []
    for m in TABLE:
        r = c.loc[m]
        rows.append(f"{LABELS.get(m, m)} & {int(r.scaled_Green)} & {int(r.scaled_Yellow)} & {int(r.scaled_Red)} & {int(r.binomial_Green)} & {int(r.binomial_Yellow)} & {int(r.binomial_Red)} \\\\")
    tab = ('% Generated by research/r8_basel_binomial/displays.py; do not edit.\n'
           '\\begin{tabular}{lrrrrrr}\n\\toprule\n & \\multicolumn{3}{c}{Scaled to 250} & \\multicolumn{3}{c}{Binomial at $n_{\\mathrm{test}}$} \\\\\n'
           '\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\nMethod & Green & Yellow & Red & Green & Yellow & Red \\\\\n\\midrule\n'
           + '\n'.join(rows) + '\n\\bottomrule\n\\end{tabular}\n')
    return num, tab

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    num, tab = build(); targets = {OUT / 'numbers_basel.tex': num, OUT / 'tab_basel.tex': tab}
    if a.check:
        bad = [str(p) for p, t in targets.items() if not p.exists() or p.read_text() != t]
        print(json.dumps(dict(status='pass' if not bad else 'FAIL', stale=bad))); sys.exit(1 if bad else 0)
    for p, t in targets.items(): p.write_text(t)
    rec = dict(inputs={n: hashlib.sha256((ART / n).read_bytes()).hexdigest() for n in ['zone_counts.csv', 'ceilings.csv']},
               outputs={p.name: hashlib.sha256(t.encode()).hexdigest() for p, t in targets.items()})
    (ART / 'displays.json').write_text(json.dumps(rec, indent=2) + '\n'); print(json.dumps(rec, indent=2))
if __name__ == '__main__': main()
