#!/usr/bin/env python3
"""Table: the sampling dose-response for Chronos-T5.

Reads the raw dose-response grid produced by
`analysis/chronos_sampling/run_dose_response.py` -- 2 checkpoints x 4 assets x
8 sampling configurations x 200 dates, 1000 draws per cell, with context, seed
and weights held fixed across configurations -- and emits the table the paper
prints.

Dispersion is the ratio of predictive standard deviation to the asset's 250-day
realised volatility; 1.0 is the target. The mean over the 800 (asset, date)
cells of a configuration is reported, because the question is what a
practitioner's sensitivity analysis would see on average, not what a typical day
looks like; the median is written to the CSV alongside it and tells the same
story.

Outputs: tab_dose_response.tex, tab_dose_response.csv
"""
from pathlib import Path

import pandas as pd

BASE = Path(__file__).resolve().parent.parent.parent
SRC = BASE / "analysis" / "chronos_sampling" / "dose_response.csv"
OUT = Path(__file__).resolve().parent

ORDER = ["top_k=50 (default)", "top_k=200", "top_k=1000", "top_k=4094 (full vocab)",
         "temp=0.5 @ k=50", "temp=2.0 @ k=50", "top_p=0.9 @ k=50", "top_p=0.99 @ k=50"]

LABEL = {
    "top_k=50 (default)":      r"\texttt{top\_k} $=50$ \emph{(default)}",
    "top_k=200":               r"\texttt{top\_k} $=200$",
    "top_k=1000":              r"\texttt{top\_k} $=1000$",
    "top_k=4094 (full vocab)": r"\texttt{top\_k} $=4094$ (full vocabulary)",
    "temp=0.5 @ k=50":         r"temperature $0.5$, at \texttt{top\_k} $=50$",
    "temp=2.0 @ k=50":         r"temperature $2.0$, at \texttt{top\_k} $=50$",
    "top_p=0.9 @ k=50":        r"\texttt{top\_p} $=0.9$, at \texttt{top\_k} $=50$",
    "top_p=0.99 @ k=50":       r"\texttt{top\_p} $=0.99$, at \texttt{top\_k} $=50$",
}


def main() -> int:
    df = pd.read_csv(SRC)
    df["disp"] = df["pred_std"] / df["realised_sd"]

    g = (df.groupby(["cell", "model"])
           .agg(disp_mean=("disp", "mean"), disp_med=("disp", "median"),
                nd_med=("n_distinct", "median"), nd_min=("n_distinct", "min"),
                nd_max=("n_distinct", "max"), n=("disp", "size"))
           .reset_index())
    g["cell"] = pd.Categorical(g["cell"], categories=ORDER, ordered=True)
    g = g.sort_values(["cell", "model"])
    g.to_csv(OUT / "tab_dose_response.csv", index=False)

    wide = g.pivot(index="cell", columns="model",
                   values=["disp_mean", "nd_med", "nd_min", "nd_max"])
    rows = []
    for cell in ORDER:
        s = wide.loc[cell]
        nd_lo = int(min(s[("nd_min", "Chronos-Small")], s[("nd_min", "Chronos-Mini")]))
        nd_hi = int(max(s[("nd_max", "Chronos-Small")], s[("nd_max", "Chronos-Mini")]))
        nd = str(nd_lo) if nd_lo == nd_hi else f"{nd_lo}--{nd_hi}"
        small = f'{s[("disp_mean", "Chronos-Small")]:.3f}'
        mini = f'{s[("disp_mean", "Chronos-Mini")]:.3f}'
        if cell == "top_k=50 (default)":
            small, mini, nd = (rf"\textbf{{{v}}}" for v in (small, mini, nd))
        rows.append(f"{LABEL[cell]} & {small} & {mini} & {nd} \\\\")

    tex = ["% Generated by Quantlets/CO_chronos_sampling/run_dose_table.py",
           r"\begin{tabular}{lccc}", r"\toprule",
           r"Sampling configuration & \multicolumn{2}{c}{Dispersion} & Distinct values \\",
           r"\cmidrule(lr){2-3}",
           r" & Chronos-Small & Chronos-Mini & out of 1000 draws \\", r"\midrule",
           *rows[:4], r"\midrule", *rows[4:], r"\bottomrule", r"\end{tabular}"]
    (OUT / "tab_dose_response.tex").write_text("\n".join(tex) + "\n", encoding="utf-8")
    print("\n".join(tex))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
