#!/usr/bin/env python3
"""Table: violation rate against nominal level, sampled default vs analytic.

The point of the table is the SHAPE of the response to alpha, not its level. A
series whose exceedance rate is nearly invariant to the level it was asked for is
not reporting a quantile, and that is visible without a benchmark or a backtest.

Reads the panel evaluation (24 assets, four levels, 70/30 chronological split,
raw forecasts with no recalibration of any kind) and reports, per model and
level, the mean violation rate across assets and the number of assets passing
Kupiec at 5%.

Outputs: tab_alpha_response.tex, tab_alpha_response.csv
"""
from pathlib import Path

import pandas as pd

BASE = Path(__file__).resolve().parent.parent.parent
SRC = BASE / "Quantlets" / "CO_full_evaluation" / "results" / "all_results.csv"
OUT = Path(__file__).resolve().parent

ALPHAS = [0.01, 0.025, 0.05, 0.10]
ROWS = [("Chronos-Small",   r"Chronos-Small, sampled at the default"),
        ("Chronos-Small-A", r"Chronos-Small, read analytically"),
        ("Chronos-Mini",    r"Chronos-Mini, sampled at the default"),
        ("Chronos-Mini-A",  r"Chronos-Mini, read analytically")]


def main() -> int:
    df = pd.read_csv(SRC)
    g = (df.groupby(["model", "alpha"])
           .agg(pihat=("pihat_raw", "mean"), kupiec=("p_kup_raw", lambda s: int((s > 0.05).sum())),
                n=("pihat_raw", "size"))
           .reset_index())
    g["ratio"] = g["pihat"] / g["alpha"]
    g[g["model"].isin([m for m, _ in ROWS])].to_csv(OUT / "tab_alpha_response.csv", index=False)

    def cells(model, field, fmt):
        out = []
        for a in ALPHAS:
            r = g[(g["model"] == model) & (g["alpha"] == a)]
            out.append(fmt(r.iloc[0]) if len(r) else "--")
        return out

    lines = ["% Generated by Quantlets/CO_chronos_sampling/run_alpha_response.py",
             r"\footnotesize",
             r"\setlength{\tabcolsep}{4pt}",
             r"\begin{tabular}{@{}p{4.3cm}cccc cccc@{}}", r"\toprule",
             r"& \multicolumn{4}{c}{Violation rate $\hat\pi(\alpha)$}"
             r" & \multicolumn{4}{c}{Kupiec passes, of 24} \\",
             r"\cmidrule(lr){2-5}\cmidrule(lr){6-9}",
             r"& $0.01$ & $0.025$ & $0.05$ & $0.10$"
             r" & $0.01$ & $0.025$ & $0.05$ & $0.10$ \\", r"\midrule"]
    for model, label in ROWS:
        pis = cells(model, "pihat", lambda r: f"{r['pihat']:.4f}")
        kup = cells(model, "kupiec", lambda r: f"{int(r['kupiec'])}")
        lines.append(f"{label} & " + " & ".join(pis) + " & " + " & ".join(kup) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\normalsize"]
    (OUT / "tab_alpha_response.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))

    print("\n--- ratio pihat/alpha (the residual's shape) ---")
    for model, label in ROWS:
        r = [f"{g[(g['model']==model)&(g['alpha']==a)]['ratio'].iloc[0]:.2f}" for a in ALPHAS]
        print(f"  {label:44s} " + "  ".join(r))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
