#!/usr/bin/env python3
"""Table: block-bootstrap confidence intervals for the conformal threshold.

`qV_bootstrap_ci.csv` is produced by `scripts/qV_block_bootstrap.py`. The LaTeX
table it feeds had no producer -- it was maintained by hand, which is why it
still showed a seven-forecaster panel with Chronos sampled at the checkpoint
default and a 'Replacement' column keyed to a taxonomy the paper has withdrawn.

The R column stays, because the ratio is a useful description of how much of a
forecast the correction replaces. The Yes/No verdict on it does not.

Output: tab_qV_bootstrap_ci.tex
"""
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
SRC = HERE / "qV_bootstrap_ci.csv"

LABEL = {
    "Chronos-Small-A": r"Chronos-Small\textsuperscript{a}",
    "TimesFM-2.5": r"TimesFM~2.5",
    "Moirai-2.0": r"Moirai~2.0",
    "Moirai-1.1": r"Moirai~1.1",
    "Lag-Llama": r"Lag-Llama",
    "GJR-GARCH": r"GJR-GARCH",
    "GJR-GARCH-t": r"GJR-GARCH-$t$",
    "GARCH-N": r"GARCH-N",
}


def num(x: float, dp: int = 3) -> str:
    """Three decimals, leading zero stripped, minus as a maths minus."""
    s = f"{abs(x):.{dp}f}"
    s = s[1:] if s.startswith("0.") else s
    return f"$-${s}" if x < 0 else s


def main() -> int:
    df = pd.read_csv(SRC)
    assets = list(dict.fromkeys(df["asset"]))
    models = list(dict.fromkeys(df["model"]))

    # The file is \input directly by the manuscript, so it carries its own
    # table environment and caption, as the hand-maintained version did.
    lines = ["% Generated by Quantlets/CO_robustness/run_qV_bootstrap_table.py",
             r"\begin{table}[htbp]", r"\centering", r"\scriptsize",
             r"\caption{Block-bootstrap 95\% confidence intervals for the conformal",
             r"threshold $\qVstat$ across six representative assets and eight",
             r"forecasters. Stationary block bootstrap",
             r"\citep{politis1994stationary}, $B = 1{,}000$ replications,",
             r"expected block length $\ell = 50$, seeded per (asset, model).",
             r"$R = |\qVstat|/|\widehat{\VaR}_{\mathrm{raw}}|$: the size of the",
             r"correction relative to the threshold it adjusts.",
             r"\textsuperscript{a}Read analytically from the checkpoint's",
             r"predictive distribution rather than sampled from it.}",
             r"\label{tab:qV_bootstrap_ci}",
             r"\begin{tabular}{@{}ll rrrr@{}}", r"\hline\hline",
             r"Asset & Model & $\qVstat$ & 95\% CI & SE & $R$ \\", r"\hline"]
    for i, asset in enumerate(assets):
        if i:
            lines.append(r"\hline")
        lines.append(rf"\multicolumn{{6}}{{@{{}}l}}{{\textit{{{asset}}}}} \\[2pt]")
        sub = df[df["asset"] == asset].set_index("model")
        for m in models:
            if m not in sub.index:
                continue
            r = sub.loc[m]
            ci = "$[" + num(r["qV_lo"]) + r",\;" + num(r["qV_hi"]) + "]$"
            lines.append(f"& {LABEL.get(m, m)} & {num(r['qV_point'])} & {ci} & "
                         f"{num(r['qV_se'])} & {r['R']:.2f} \\\\")
    lines += [r"\hline\hline", r"\end{tabular}", r"\end{table}"]
    (HERE / "tab_qV_bootstrap_ci.tex").write_text("\n".join(lines) + "\n",
                                                  encoding="utf-8")
    print("\n".join(lines[:12]))
    print(f"\n... {len(assets)} assets x {len(models)} forecasters")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
