#!/usr/bin/env python3
"""Is the 1% failure created by the model, or by the extrapolation below its grid?

The interface claim is that a nine-decile grid contains no 1% quantile, so
whatever a quantile-grid model reports as VaR_0.01 was manufactured by a closure
rule downstream of the model. If that is right, the failure should appear
*only* below the grid.

Every model in the panel emits a forecast at u = 0.10. For the grid models that
level is NATIVE -- 0.10 is the lowest point the model actually predicts. For
alpha = 0.01 it is EXTRAPOLATED. So each grid model supplies its own control:

    coverage at u = 0.10   what the model predicts
    coverage at u = 0.01   what the closure predicts

If a grid model is well calibrated at 0.10 and catastrophically miscalibrated at
0.01, the defect is in the closure step, holding architecture, corpus and
checkpoint exactly fixed. No cross-model comparison is involved, and no
architectural control is required.

The sample-based models are the reference: for them both levels are native, so
neither should show the break.

This is a within-model intervention on data already on disk. The nine-decile
collapse of Moirai 1.1 -- re-evaluating its mixture-distribution forecasts on a
decile grid and applying Moirai 2.0's closure -- is the stronger design but is
NOT runnable here: only the lower-tail quantiles were stored, never the deciles
or the raw samples, so it requires re-running inference.

Output: analysis/interface/
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

BASE = Path(__file__).resolve().parent.parent.parent
DATA = BASE / "cfp_ijf_data"
OUT = Path(__file__).resolve().parent

sys.path.insert(0, str(BASE / "analysis" / "ae_point4"))
from run_ae_point4 import MODELS, SYMBOLS, kupiec_p  # noqa: E402

# How each model's alpha = 0.01 forecast is obtained. Verified against the
# manuscript's Section 3.2 and the pipeline notebooks.
INTERFACE = {
    "Chronos-Small": ("sample", "native"), "Chronos-Mini": ("sample", "native"),
    "Lag-Llama": ("sample", "native"), "Moirai-1.1": ("sample", "native"),
    "TimesFM-2.5": ("grid-9", "extrapolated"), "Moirai-2.0": ("grid-9", "extrapolated"),
    "GJR-GARCH": ("parametric", "native"), "GARCH-N": ("parametric", "native"),
    "Hist-Sim": ("empirical", "native"), "EWMA": ("parametric", "native"),
}


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    for model, (subdir, suffix) in MODELS.items():
        for sym in SYMBOLS:
            ret = pd.read_csv(DATA / "returns" / f"{sym}.csv", index_col=0,
                              parse_dates=True)
            ret.columns = ["r"]
            name = f"{sym}.parquet" if suffix is None else f"{sym}_{suffix}.parquet"
            fp = DATA / subdir / name
            if not fp.exists():
                continue
            fc = pd.read_parquet(fp)
            common = ret.index.intersection(fc.index)
            r = ret.loc[common, "r"].values
            out = {"model": model, "asset": sym,
                   "interface": INTERFACE[model][0],
                   "alpha001_origin": INTERFACE[model][1]}
            for lvl, col in ((0.10, "VaR_0.1"), (0.01, "VaR_0.01")):
                if col not in fc.columns:
                    continue
                q = fc.loc[common, col].values
                m = np.isfinite(q)
                rr, qq = r[m], q[m]
                if len(rr) < 100:
                    continue
                v = int(np.sum(rr < qq))
                out[f"pihat_{lvl:g}"] = v / len(rr)
                out[f"p_kup_{lvl:g}"] = kupiec_p(v, len(rr), lvl)
                out[f"n_{lvl:g}"] = len(rr)
            rows.append(out)
        print(f"  {model}", file=sys.stderr)

    df = pd.DataFrame(rows)
    df.to_csv(OUT / "native_vs_extrapolated.csv", index=False)

    g = df.groupby(["model", "interface", "alpha001_origin"]).agg(
        n_assets=("asset", "size"),
        pi_at_10pct=("pihat_0.1", "mean"),
        pi_at_1pct=("pihat_0.01", "mean"),
    ).reset_index()
    g["ratio_10pct"] = g["pi_at_10pct"] / 0.10
    g["ratio_1pct"] = g["pi_at_1pct"] / 0.01
    g = g.sort_values("ratio_1pct")

    L = ["# Native versus extrapolated: where the failure is created", "",
         "Generated by `analysis/interface/run_native_vs_extrapolated.py`.", "",
         "Each model is evaluated at the level it natively predicts (u = 0.10, "
         "the lowest point of a nine-decile grid) and at the level the audit "
         "targets (alpha = 0.01). For the two grid models the second is not a "
         "model output at all: it is produced by a Student-$t$ closure fitted "
         "to the grid. Every other model predicts both levels directly.", "",
         "| Model | interface | 1% origin | π̂ at u=0.10 | ×nominal | π̂ at α=0.01 | ×nominal |",
         "|---|---|---|---|---|---|---|"]
    for _, r in g.iterrows():
        L.append(f"| {r['model']} | {r['interface']} | {r['alpha001_origin']} | "
                 f"{r['pi_at_10pct']:.4f} | {r['ratio_10pct']:.2f} | "
                 f"**{r['pi_at_1pct']:.4f}** | **{r['ratio_1pct']:.1f}** |")
    L.append("")

    grid = g[g["interface"] == "grid-9"]
    rest = g[g["interface"] != "grid-9"]
    L += ["## Reading", "",
          f"Grid models at their own lowest grid point: mean π̂ = "
          f"{grid['pi_at_10pct'].mean():.4f} against a nominal 0.10 "
          f"({grid['ratio_10pct'].mean():.2f}× nominal). At the extrapolated "
          f"level: mean π̂ = {grid['pi_at_1pct'].mean():.4f} against 0.01 "
          f"({grid['ratio_1pct'].mean():.0f}× nominal).", "",
          f"All other models at u = 0.10: {rest['ratio_10pct'].mean():.2f}× "
          f"nominal; at α = 0.01: {rest['ratio_1pct'].mean():.1f}× nominal.", ""]
    (OUT / "MEMO.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
