"""Manuscript macros for the near-break-even costs of Proposition 4.3 (count obstruction).

Reads artifacts/r8_count_law/exact_witness.json (exact rationals) and writes
source/sections_r8/numbers_count.tex. All arithmetic is exact; only the final
decimal rendering rounds. --check regenerates into memory and compares with disk.
"""
import argparse, hashlib, json, sys
from fractions import Fraction
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
IN = ROOT / 'artifacts/r8_count_law/exact_witness.json'
OUT = ROOT / 'source/sections_r8/numbers_count.tex'
RECEIPT = ROOT / 'artifacts/r8_count_display/displays.json'


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def build():
    w = json.loads(IN.read_text())
    assert w['status'] == 'passed' and w['arithmetic'] == 'exact rational'
    n = int(w['n']); p = Fraction(w['p']); d = Fraction(w['delta'])
    a0 = Fraction(w['iid_cost']); ah = Fraction(w['renewal_cost']); b = Fraction(w['raw_regret'])
    assert b == d * d / 2, 'raw regret must equal d^2/2'
    assert a0 - b == Fraction(w['iid_loss_change']) and ah - b == Fraction(w['renewal_loss_change'])
    assert ah < b < a0
    omega = p * (1 - p)                  # independent pairs at every nonzero lag
    f_star = Fraction(1)                 # uniform marginal: score density is one at c_* = d
    leading = omega / (2 * n * f_star)   # Omega / (2 n f_*), Proposition 4.1
    def x1e5(v): return f'{float(v * 100000):.3f}'
    def pct(v): return f'{float(100 * v):.2f}'
    mac = dict(
        CountIidCost=x1e5(a0), CountRenewalCost=x1e5(ah), CountRemovable=x1e5(b), CountLeading=x1e5(leading),
        CountIidRelPct=pct((a0 - b) / b), CountRenewalRelPct=pct((b - ah) / b),  # magnitude; the renewal cost lies below d^2/2
        CountGapPct=pct((a0 - ah) / b), CountLeadingOverIid=f'{float(leading / a0):.2f}',
        CountN=str(n))
    tex = ('% Generated by research/r8_count_display/displays.py from artifacts/r8_count_law/exact_witness.json; do not edit.\n'
           '% Costs are multiplied by 1e5; relative values are percentages of the removable loss d^2/2.\n'
           + ''.join(f'\\newcommand{{\\n{k}}}{{{v}}}\n' for k, v in mac.items()))
    return tex, mac


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    tex, mac = build()
    if a.check:
        rec = json.loads(RECEIPT.read_text())
        ok = OUT.exists() and OUT.read_text() == tex and rec['inputs'][str(IN.relative_to(ROOT))] == sha(IN) \
            and rec['outputs'][OUT.name] == hashlib.sha256(tex.encode()).hexdigest() and rec['macros'] == mac
        print(json.dumps(dict(status='pass' if ok else 'FAIL', macros=mac))); sys.exit(0 if ok else 1)
    OUT.write_text(tex)
    rec = dict(producer_sha256=sha(__file__), inputs={str(IN.relative_to(ROOT)): sha(IN)},
               outputs={OUT.name: sha(OUT)}, macros=mac)
    RECEIPT.parent.mkdir(parents=True, exist_ok=True)
    RECEIPT.write_text(json.dumps(rec, indent=2) + '\n'); print(json.dumps(rec, indent=2))


if __name__ == '__main__':
    main()
