"""Display of the estimation-window sweep in source/analysis/phase3_windows (PROTOCOL.md).

Reads window_sensitivity.csv; writes artifacts/r8_window_sweep/sweep_summary.csv (with --write) and
source/sections_r8/{numbers_windows,tab_windows_sweep}.tex. --check recomputes and compares.
"""
import argparse, hashlib, json, sys
from pathlib import Path
import numpy as np, pandas as pd
ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / 'source/analysis/phase3_windows/window_sensitivity.csv'; INV = ROOT / 'artifacts/r8_commodity_etp/panel/base/quality/asset_inventory.csv'
ART = ROOT / 'artifacts/r8_window_sweep'; OUT = ROOT / 'source/sections_r8'
MODELS = ['GJR-GARCH', 'GARCH-N', 'EWMA', 'Hist-Sim']; LABELS = {'GJR-GARCH': 'GJR-N', 'Hist-Sim': 'Historical simulation'}
WINDOWS = [250, 500, 1000]; WNAME = {250: 'TwoFifty', 500: 'FiveHundred', 1000: 'Thousand'}; MNAME = {'GJR-GARCH': 'Gjr', 'GARCH-N': 'GarchN', 'EWMA': 'Ewma', 'Hist-Sim': 'Hs'}

def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()

def summarise():
    w = pd.read_csv(SRC); assert len(w) == 288 and set(w.model) == set(MODELS) and set(w.w) == set(WINDOWS)
    assert w.groupby(['model', 'w']).asset.nunique().eq(24).all()
    rows = []
    for m in MODELS:
        for k in WINDOWS:
            g = w[(w.model == m) & (w.w == k)]
            rows.append({'model': m, 'w': k, 'series': len(g), 'gain_x1e4': 1e4 * g.dQS.mean(), 'raw_pi_pct': 100 * g.pihat_raw.mean(), 'cp_pi_pct': 100 * g.pihat_cp.mean(),
                         'raw_green': int((g.TL_raw == 'Green').sum()), 'cp_green': int((g.TL_cp == 'Green').sum()), 'series_gain_positive': int((g.dQS > 0).sum()),
                         'convergence_failures': int(g.convergence_failures.sum()), 'mean_n_test': g.n_test.mean()})
    inv = pd.read_csv(INV); old = inv[inv.old_last.notna()]
    prov = {'old_last_unique': sorted(old.old_last.unique()), 'series_unchanged_on_overlap': sorted(old[old.overlap_changed_above_1e_12 == 0].asset),
            'series_changed_on_overlap': sorted(old[old.overlap_changed_above_1e_12 > 0].asset), 'series_without_old_vintage': sorted(inv[inv.old_last.isna()].asset),
            'sweep_series': sorted(w.asset.unique()), 'series_not_in_current_panel': sorted(set(w.asset) - set(inv.asset)),
            'series_without_overlap_record': sorted(set(w.asset) & set(inv[inv.old_last.isna()].asset))}
    return pd.DataFrame(rows), prov

def build(summary, prov):
    s = summary.set_index(['model', 'w']); m = {}
    for mod in MODELS:
        for k in WINDOWS:
            r = s.loc[(mod, k)]
            m[f'{MNAME[mod]}Gain{WNAME[k]}'] = f"{r.gain_x1e4:.3f}"; m[f'{MNAME[mod]}RawPi{WNAME[k]}'] = f"{r.raw_pi_pct:.2f}"; m[f'{MNAME[mod]}CpPi{WNAME[k]}'] = f"{r.cp_pi_pct:.2f}"
            m[f'{MNAME[mod]}RawGreen{WNAME[k]}'] = str(int(r.raw_green)); m[f'{MNAME[mod]}Positive{WNAME[k]}'] = str(int(r.series_gain_positive))
    m['Rows'] = str(int(summary.series.sum())); m['Series'] = '24'; m['Failures'] = str(int(summary.convergence_failures.sum()))
    assert len(prov['old_last_unique']) == 1; m['VintageEnd'] = pd.Timestamp(prov['old_last_unique'][0]).strftime('%-d %B %Y')
    m['Unchanged'] = str(len(prov['series_unchanged_on_overlap'])); m['Changed'] = str(len(prov['series_changed_on_overlap'])); m['ChangedList'] = ', '.join(prov['series_changed_on_overlap'])
    m['ReplacedList'] = ', '.join(prov['series_not_in_current_panel']); m['Replaced'] = str(len(prov['series_not_in_current_panel']))
    m['NoRecordList'] = ', '.join(prov['series_without_overlap_record']); m['NoRecord'] = str(len(prov['series_without_overlap_record']))
    num = '% Generated by research/r8_window_sweep/displays.py; do not edit.\n' + ''.join(f'\\newcommand{{\\nWin{k}}}{{{v}}}\n' for k, v in m.items())
    rows = []
    for mod in MODELS:
        cells = [f"{s.loc[(mod, k)].gain_x1e4:.3f} & {s.loc[(mod, k)].raw_pi_pct:.2f} & {s.loc[(mod, k)].cp_pi_pct:.2f}" for k in WINDOWS]
        rows.append(f"{LABELS.get(mod, mod)} & " + ' & '.join(cells) + ' \\\\')
    tab = ('% Generated by research/r8_window_sweep/displays.py; do not edit.\n\\begin{tabular}{lrrrrrrrrr}\n\\toprule\n'
           ' & \\multicolumn{3}{c}{$w=250$} & \\multicolumn{3}{c}{$w=500$} & \\multicolumn{3}{c}{$w=1000$} \\\\\n\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\\cmidrule(lr){8-10}\n'
           'Model & Gain & $\\pi_{\\mathrm{raw}}$ & $\\pi_{\\mathrm{cp}}$ & Gain & $\\pi_{\\mathrm{raw}}$ & $\\pi_{\\mathrm{cp}}$ & Gain & $\\pi_{\\mathrm{raw}}$ & $\\pi_{\\mathrm{cp}}$ \\\\\n\\midrule\n' + '\n'.join(rows) + '\n\\bottomrule\n\\end{tabular}\n')
    return num, tab

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    summary, prov = summarise(); num, tab = build(summary, prov)
    targets = {OUT / 'numbers_windows.tex': num, OUT / 'tab_windows_sweep.tex': tab}
    if a.check:
        saved = pd.read_csv(ART / 'sweep_summary.csv'); assert list(saved.columns) == list(summary.columns)
        for c in summary.columns:
            if summary[c].dtype.kind in 'fi': assert np.allclose(saved[c].to_numpy(float), summary[c].to_numpy(float), atol=1e-10), c
            else: assert saved[c].astype(str).tolist() == summary[c].astype(str).tolist(), c
        bad = [str(p) for p, t in targets.items() if not p.exists() or p.read_text() != t]
        print(json.dumps(dict(status='pass' if not bad else 'FAIL', stale=bad))); sys.exit(1 if bad else 0)
    ART.mkdir(parents=True, exist_ok=True); summary.to_csv(ART / 'sweep_summary.csv', index=False)
    for p, t in targets.items(): p.write_text(t)
    (ART / 'run.json').write_text(json.dumps({'protocol_sha256': sha(Path(__file__).with_name('PROTOCOL.md')), 'producer_sha256': sha(__file__),
        'inputs': {'window_sensitivity.csv': sha(SRC), 'asset_inventory.csv': sha(INV)}, 'provenance': prov,
        'outputs': {p.name: hashlib.sha256(t.encode()).hexdigest() for p, t in targets.items()}, 'python': sys.version}, indent=2) + '\n')
    print(summary.to_string()); print(json.dumps(prov, indent=1))
if __name__ == '__main__': main()
