#!/usr/bin/env python3
r"""Table 1 of the Monte Carlo section, emitted from grid.csv.

The table was hand-authored with 151 typed figures, in a file guard 2 never
read: its DOCS list held the two top-level documents and not the two \input
section files. Every figure reproduces from analysis/k2_sim/grid.csv, so the
table is emitted rather than transcribed and the literals disappear.

Unit: one row is a data-generating process; one column pair is a sample size.
5 DGPs x 5 sample sizes, from a grid of 500 replications per cell.

    python analysis/k2_sim/emit_mc_table.py
    python analysis/k2_sim/emit_mc_table.py --controls
"""
from __future__ import annotations

import argparse
import numpy as np
import pandas as pd
from pathlib import Path

HERE = Path(__file__).resolve().parent
ALPHA = 0.01
TS = [500, 1000, 2000, 5000, 10000]
LABEL = {"normal": "Normal (correct)", "t5": r"Student-$t$(5)",
         "t3": r"Student-$t$(3)", "skewt3": r"Skewed-$t$(3, $-0.5$)",
         "mixnormal": "Mixture of Normals"}
# The population violation rate of each DGP under a Normal-innovation
# forecaster, which is a property of the design and not of the run.
POP = {"normal": 0.0100, "t5": 0.0150, "t3": 0.0136,
       "skewt3": 0.0233, "mixnormal": 0.0125}
RED, GRN, YEL = "\033[31m", "\033[32m", "\033[33m"; OFF = "\033[0m"


def grid() -> pd.DataFrame:
    return pd.read_csv(HERE / "grid.csv").set_index(["dgp", "T"])


def _fmt_t(t: int) -> str:
    return f"{t:,}".replace(",", "{,}")


def build(g: pd.DataFrame) -> str:
    L = ["% Generated by analysis/k2_sim/emit_mc_table.py -- do not edit by hand.",
         r"\begin{tabular}{@{}lc rrrrr rrrrr@{}}", r"\toprule",
         r"& population", r"& \multicolumn{5}{c}{corrected $\hat\pi$}",
         r"& \multicolumn{5}{c}{raw forecasts in the green zone (\%)} \\",
         r"\cmidrule(lr){3-7}\cmidrule(l){8-12}",
         r"Innovations & $\hat\pi$",
         "& " + " & ".join(f"${_fmt_t(t)}$" for t in TS),
         "& " + " & ".join(f"${_fmt_t(t)}$" for t in TS) + r" \\",
         r"\midrule"]
    for d, lab in LABEL.items():
        cor = " & ".join(f"{g.loc[(d, t), 'Corr_pi']:.4f}" for t in TS)
        grn = " & ".join(f"{g.loc[(d, t), 'RawGreen']:.1f}" for t in TS)
        L.append(f"{lab} & {POP[d]:.4f} & {cor} & {grn} " + r"\\")
    L += [r"\midrule",
          r"\multicolumn{12}{@{}l}{\textit{Mean $\qVstat$ (left) and its "
          r"standard deviation across replications (right)}} \\[2pt]"]
    for d, lab in LABEL.items():
        mu = " & ".join(f"{g.loc[(d, t), 'Mean_qV']:.5f}" for t in TS)
        sd = " & ".join(f"{g.loc[(d, t), 'Std_qV']:.5f}" for t in TS)
        L.append(f"{lab} & --- & {mu} & {sd} " + r"\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


def control_reproduces_shipped() -> bool:
    """Every figure in the shipped table must appear in the emitted one.

    This is the control that matters: if the emitter and the hand-authored
    table disagree anywhere, the table was never a transcription of the
    artefact and emitting it would silently change published numbers.
    """
    import re
    shipped = (HERE.parent.parent / "sections" / "sec5_montecarlo.tex").read_text(encoding="utf-8")
    i = shipped.find(r"\begin{tabular}")
    j = shipped.find(r"\end{tabular}")
    if i < 0:
        return True                       # already replaced by \input
    old = set(re.findall(r"\d+\.\d+", shipped[i:j]))
    new = set(re.findall(r"\d+\.\d+", build(grid())))
    return old <= new


def control_grid_is_complete() -> bool:
    g = grid()
    return all((d, t) in g.index for d in LABEL for t in TS)


def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--controls", action="store_true")
    a = ap.parse_args()
    ok = True
    for name, fn in (("the grid covers every cell the table prints", control_grid_is_complete),
                     ("every shipped figure appears in the emitted table",
                      control_reproduces_shipped)):
        if fn(): print(f"  {YEL}ctrl{OFF}   {name}")
        else: print(f"  {RED}FAIL{OFF}   control does not fire: {name}"); ok = False
    if not ok: return 2
    if a.controls: return 0
    out = HERE / "tab_mc_grid.tex"
    out.write_text(build(grid()), encoding="utf-8")
    print(f"\n  {GRN}pass{OFF}   wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
