"""Manuscript displays of the width and severity study.

Reads artifacts/r8_economics/{widths,severity,by_year}.csv; writes source/sections_r8/numbers_econ.tex and tab_econ.tex. --check compares.
"""
import argparse, hashlib, json, sys
from pathlib import Path
import pandas as pd
ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / 'artifacts/r8_economics'; OUT = ROOT / 'source/sections_r8'
LABELS = {'Rolling250': 'Rolling 250', 'Rolling500': 'Rolling 500', 'Selected-rolling': 'Selected rolling', 'Gate-selected-rolling': 'Coverage-gated rolling',
          'Loss-gate': 'Loss gate', 'Past-minimum': 'Past-loss minimum', 'State-L1': 'Regularised state'}
TABLE = ['Raw', 'Shift-CP', 'Shift-ERM', 'Vol-ERM', 'State-L1', 'POT-Shift', 'POT-Vol', 'Rolling250', 'Rolling500', 'Selected-rolling', 'Gate-selected-rolling', 'Loss-gate', 'Past-minimum']

def build():
    w = pd.read_csv(ART / 'widths.csv').set_index('method'); s = pd.read_csv(ART / 'severity.csv').set_index('method'); y = pd.read_csv(ART / 'by_year.csv')
    m = {}
    for meth, tag in [('Raw', 'Raw'), ('Shift-CP', 'Static'), ('Rolling250', 'Rolling'), ('Loss-gate', 'Gate')]:
        m[f'{tag}VaR'] = f"{w.loc[meth, 'pooled_mean_var_pct']:.3f}"; m[f'{tag}VaRPair'] = f"{w.loc[meth, 'pair_equal_mean_var_pct']:.3f}"
        m[f'{tag}WidenPct'] = f"{w.loc[meth, 'pooled_pct_change_vs_raw']:.1f}"; m[f'{tag}WidenPctPair'] = f"{w.loc[meth, 'pair_equal_pct_change_vs_raw']:.1f}"
        m[f'{tag}RatioMean'] = f"{w.loc[meth, 'ratio_mean']:.3f}"; m[f'{tag}RatioMedian'] = f"{w.loc[meth, 'ratio_median']:.3f}"
        m[f'{tag}RatioMax'] = f"{w.loc[meth, 'ratio_max']:.3f}"; m[f'{tag}RatioMin'] = f"{w.loc[meth, 'ratio_min']:.3f}"; m[f'{tag}Wider'] = str(int(w.loc[meth, 'pairs_wider_than_raw']))
    for meth, tag in [('Raw', 'Raw'), ('Shift-CP', 'Static')]:
        m[f'{tag}VaRMoney'] = f"{w.loc[meth, 'pooled_mean_loss_fraction_pct']:.3f}"; m[f'{tag}VaRMoneyPair'] = f"{w.loc[meth, 'pair_equal_mean_loss_fraction_pct']:.3f}"
    m['StaticWidenPctMoney'] = f"{w.loc['Shift-CP', 'pooled_loss_fraction_pct_change_vs_raw']:.1f}"
    m['Pairs'] = str(int(w.loc['Raw', 'pairs'])); m['PairDays'] = f"{int(w.loc['Raw', 'pair_days']):,}"
    for meth, tag in [('Raw', 'Raw'), ('Shift-CP', 'Static'), ('Rolling250', 'Rolling')]:
        m[f'{tag}Exceed'] = f"{s.loc[meth, 'pooled_mean_exceedance_pct']:.2f}"; m[f'{tag}BreachLoss'] = f"{s.loc[meth, 'pooled_mean_loss_on_breach_pct']:.2f}"; m[f'{tag}Breaches'] = f"{int(s.loc[meth, 'breaches']):,}"
    m['YearWidenMin'] = f"{y['pct_change'].min():.1f}"; m['YearWidenMax'] = f"{y['pct_change'].max():.1f}"
    m['YearWidenMinYear'] = str(int(y.loc[y['pct_change'].idxmin(), 'year'])); m['YearWidenMaxYear'] = str(int(y.loc[y['pct_change'].idxmax(), 'year']))
    # Static multiplied by (1 + widening) as a ratio, for the capital arithmetic in the text.
    m['StaticRatioPooled'] = f"{w.loc['Shift-CP', 'pooled_mean_var_pct'] / w.loc['Raw', 'pooled_mean_var_pct']:.4f}"
    num = '% Generated by research/r8_economics/displays.py; do not edit.\n' + ''.join(f'\\newcommand{{\\nEcon{k}}}{{{v}}}\n' for k, v in m.items())
    rows = [f"{LABELS.get(t, t)} & {w.loc[t, 'pooled_mean_var_pct']:.3f} & {w.loc[t, 'pair_equal_mean_var_pct']:.3f} & {w.loc[t, 'ratio_median']:.3f} & {w.loc[t, 'ratio_max']:.3f} & {int(w.loc[t, 'pairs_wider_than_raw'])} \\\\" for t in TABLE]
    tab = ('% Generated by research/r8_economics/displays.py; do not edit.\n\\begin{tabular}{lrrrrr}\n\\toprule\n'
           'Method & Pooled & Pair-equal & Median ratio & Max ratio & Wider \\\\\n\\midrule\n' + '\n'.join(rows) + '\n\\bottomrule\n\\end{tabular}\n')
    return num, tab

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    num, tab = build(); targets = {OUT / 'numbers_econ.tex': num, OUT / 'tab_econ.tex': tab}
    if a.check:
        bad = [str(p) for p, t in targets.items() if not p.exists() or p.read_text() != t]
        print(json.dumps(dict(status='pass' if not bad else 'FAIL', stale=bad))); sys.exit(1 if bad else 0)
    for p, t in targets.items(): p.write_text(t)
    rec = dict(inputs={n: hashlib.sha256((ART / n).read_bytes()).hexdigest() for n in ['widths.csv', 'severity.csv', 'by_year.csv']},
               outputs={p.name: hashlib.sha256(t.encode()).hexdigest() for p, t in targets.items()})
    (ART / 'displays.json').write_text(json.dumps(rec, indent=2) + '\n'); print('written')
if __name__ == '__main__': main()
