"""Generate the manuscript displays of the prespecified power analysis.

Reads artifacts/r8_power_analysis/{contrasts,decomposition,sign}.csv and writes
source/sections_r8/numbers_power.tex and source/sections_r8/tab_power.tex.
--check regenerates into memory and compares with the files on disk.
"""
import argparse, hashlib, json, sys
from pathlib import Path
import pandas as pd
ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / 'artifacts/r8_power_analysis'; OUT = ROOT / 'source/sections_r8'
LABEL = {'1_all_pairs': 'All 240 pairs', '2_classical_only': 'Classical forecasters (120)',
         '3_foundation_only': 'Foundation models (120)', '4_excluding_lag_llama': 'Excluding Lag-Llama (216)',
         '5_equities_only': 'Equities and equity ETF (110)', '6_fx_bonds_commodities': 'FX, bonds and commodities (110)',
         '7_crypto_only': 'Cryptocurrencies (20)', '8_pair_normalised': 'Pair-normalised loss (240)',
         '9_date_weighted': 'Date-weighted (240)'}

def build():
    c = pd.read_csv(ART / 'contrasts.csv'); d = pd.read_csv(ART / 'decomposition.csv').set_index('item')['value']
    s = pd.read_csv(ART / 'sign.csv').set_index('block_calendar_days')
    rows = []
    for name in LABEL:
        r20 = c[(c.contrast == name) & (c.block_calendar_days == 20)].iloc[0]
        r60 = c[(c.contrast == name) & (c.block_calendar_days == 60)].iloc[0]
        f = (lambda v: f'{v:.5f}') if name == '8_pair_normalised' else (lambda v: f'{v:.3f}')
        rows.append(f"{LABEL[name]} & {f(r60.point)} & [{f(r20.simultaneous_lower)}, {f(r20.simultaneous_upper)}] & [{f(r60.simultaneous_lower)}, {f(r60.simultaneous_upper)}] \\\\")
    tab = ('% Generated by research/r8_power_analysis/displays.py; do not edit.\n'
           '\\begin{tabular}{lrrr}\n\\toprule\nContrast & Mean & 20-day band & 60-day band \\\\\n\\midrule\n'
           + '\n'.join(rows) + '\n\\bottomrule\n\\end{tabular}\n')
    nine_60_exclude = int(((c.block_calendar_days == 60) & (c.simultaneous_upper < 0)).sum())
    nine_20_exclude = int(((c.block_calendar_days == 20) & (c.simultaneous_upper < 0)).sum())
    mac = dict(
        PowerTopShare=f"{100*float(d['top10_dates_abs_date_sum_share_of_pooled_sum']):.1f}",
        PowerTopPoint=f"{float(d['point_contrast1_block20_without_top10_abs_date_sum_x1e4']):.3f}",
        PowerVarFracTwenty=f"{100*float(d['fraction_of_bootstrap_variance_from_top10_abs_date_sum_block20']):.1f}",
        PowerVarFracSixty=f"{100*float(d['fraction_of_bootstrap_variance_from_top10_abs_date_sum_block60']):.1f}",
        PowerWithinSD=f"{float(d['average_within_pair_sd_x1e4']):.2f}",
        PowerBetweenSD=f"{float(d['between_pair_sd_of_pair_means_x1e4']):.2f}",
        PowerLagOne=f"{float(d['average_lag1_autocorrelation']):.3f}",
        PowerDates=str(int(float(d['n_distinct_calendar_dates']))),
        PowerEquityShare=f"{100*float(d['share_pair_weighted_class_Equity']):.1f}",
        PowerLagLlamaShare=f"{100*float(d['share_pair_weighted_model_Lag-Llama']):.1f}",
        PowerImproved=str(int(s.loc[60, 'pairs_improved'])),
        PowerImprovedLo=f"{float(s.loc[60, 'bootstrap_lower']):.2f}",
        PowerImprovedHi=f"{float(s.loc[60, 'bootstrap_upper']):.2f}",
        PowerExcludeTwenty=str(nine_20_exclude), PowerExcludeSixty=str(nine_60_exclude),
        PowerFamily='9')
    num = '% Generated by research/r8_power_analysis/displays.py; do not edit.\n' + ''.join(f'\\newcommand{{\\n{k}}}{{{v}}}\n' for k, v in mac.items())
    return num, tab

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    num, tab = build()
    targets = {OUT / 'numbers_power.tex': num, OUT / 'tab_power.tex': tab}
    if a.check:
        bad = [str(p) for p, t in targets.items() if not p.exists() or p.read_text() != t]
        print(json.dumps(dict(status='pass' if not bad else 'FAIL', stale=bad))); sys.exit(1 if bad else 0)
    for p, t in targets.items(): p.write_text(t)
    rec = dict(inputs={n: hashlib.sha256((ART / n).read_bytes()).hexdigest() for n in ['contrasts.csv', 'decomposition.csv', 'sign.csv']},
               outputs={p.name: hashlib.sha256(t.encode()).hexdigest() for p, t in targets.items()})
    (ART / 'displays.json').write_text(json.dumps(rec, indent=2) + '\n'); print(json.dumps(rec, indent=2))
if __name__ == '__main__': main()
