"""Manuscript displays of the ES/FZ0 study.

Reads artifacts/r8_es_fz0/{summary.csv, contrasts.csv, run.json}; writes source/sections_r8/{numbers_es,tab_es}.tex. --check compares.
"""
import argparse, hashlib, json, sys
from pathlib import Path
import pandas as pd
ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / 'artifacts/r8_es_fz0'; OUT = ROOT / 'source/sections_r8'
ROWS = [('Moirai-1.1', 'Moirai', 'Moirai-1.1'), ('Lag-Llama', 'Lag', 'Lag-Llama'), ('GJR-GARCH', 'GjrN', 'GJR-N'), ('GJR-GARCH-t', 'GjrT', 'GJR-$t$'),
        ('GARCH-N', 'GarchN', 'GARCH-N'), ('Hist-Sim', 'Hs', 'Hist-Sim'), ('EWMA', 'Ewma', 'EWMA')]

def build():
    s = pd.read_csv(ART / 'summary.csv').set_index(['model', 'method']); c = pd.read_csv(ART / 'contrasts.csv').set_index(['comparison', 'block_calendar_days'])
    run = json.loads((ART / 'run.json').read_text())['summary']
    m = {'Pairs': str(run['pairs']), 'Assets': str(run['assets']), 'TestObs': f"{run['test_observations']:,}", 'Draws': str(run['draws_per_date']), 'EsDraws': str(run['es_draws']),
         'EsWindowPoints': str(run['es_window_points']), 'NonnegDays': str(run['es_nonneg_days']), 'VarNonnegRaw': str(run['var_nonneg_raw_days']), 'VarNonnegStatic': str(run['var_nonneg_static_days'])}
    exclude_both, include_any = [], []
    lines = [r'\begingroup\setlength{\tabcolsep}{2pt}', r'\begin{tabular}{lrrrrrrr}', r'\toprule',
             r'Forecaster & FZ0 raw & FZ0 static & 60-day band & ES raw & ES static & Gap raw & Gap static \\', r'\midrule']
    for model, tag, label in ROWS:
        raw = s.loc[(model, 'Raw')]; stat = s.loc[(model, 'Static')]
        m[tag + 'RawFZ'] = f'{raw.FZ0:.4f}'; m[tag + 'StaticFZ'] = f'{stat.FZ0:.4f}'; m[tag + 'RawES'] = f'{100 * raw.ES_mean:.3f}'; m[tag + 'StaticES'] = f'{100 * stat.ES_mean:.3f}'
        m[tag + 'RawVaR'] = f'{100 * raw.VaR_mean:.3f}'; m[tag + 'StaticVaR'] = f'{100 * stat.VaR_mean:.3f}'
        m[tag + 'RawGap'] = f'{100 * raw.shortfall_gap:.3f}'; m[tag + 'StaticGap'] = f'{100 * stat.shortfall_gap:.3f}'; m[tag + 'RawExcess'] = str(int(raw.es_excess_days)); m[tag + 'StaticExcess'] = str(int(stat.es_excess_days))
        m[tag + 'RawPi'] = f'{100 * raw.pi_mean:.3f}'; m[tag + 'StaticPi'] = f'{100 * stat.pi_mean:.3f}'
        both = True
        for block, word in [(20, 'Twenty'), (60, 'Sixty')]:
            r = c.loc[(model, block)]; m[tag + 'Delta'] = f'{r.estimate:.4f}'; m[tag + 'Lo' + word] = f'{r.simultaneous_lower:.4f}'; m[tag + 'Hi' + word] = f'{r.simultaneous_upper:.4f}'
            m[tag + 'PointLo' + word] = f'{r.pointwise_lower:.4f}'; m[tag + 'PointHi' + word] = f'{r.pointwise_upper:.4f}'
            both = both and r.simultaneous_upper < 0
        (exclude_both if both else include_any).append(label)
        r = c.loc[(model, 60)]
        lines.append(f'{label} & {raw.FZ0:.4f} & {stat.FZ0:.4f} & [{r.simultaneous_lower:.4f}, {r.simultaneous_upper:.4f}] & {100 * raw.ES_mean:.3f} & {100 * stat.ES_mean:.3f} & {100 * raw.shortfall_gap:.3f} & {100 * stat.shortfall_gap:.3f}' + r' \\')
    for block, word in [(20, 'Twenty'), (60, 'Sixty')]:
        r = c.loc[('All', block)]; m['AllDelta'] = f'{r.estimate:.4f}'; m['AllLo' + word] = f'{r.simultaneous_lower:.4f}'; m['AllHi' + word] = f'{r.simultaneous_upper:.4f}'
        m['AllPointLo' + word] = f'{r.pointwise_lower:.4f}'; m['AllPointHi' + word] = f'{r.pointwise_upper:.4f}'; m['AllSd' + word] = f'{r.bootstrap_sd:.4f}'; m['Crit' + word] = f'{r.critical:.3f}'
    m['ExcludeBothCount'] = str(len(exclude_both)); m['ExcludeBothModels'] = ', '.join(exclude_both); m['IncludeAnyCount'] = str(len(include_any)); m['IncludeAnyModels'] = ', '.join(include_any) or 'none'
    normal = [tag for model, tag, _ in ROWS if s.loc[(model, 'Raw')].law == 'normal']; m['NormalGapMax'] = f"{100 * max(s.loc[(mo, 'Raw')].shortfall_gap for mo, t, _ in ROWS if t in normal):.3f}"
    m['NormalGapMin'] = f"{100 * min(s.loc[(mo, 'Raw')].shortfall_gap for mo, t, _ in ROWS if t in normal):.3f}"
    r = c.loc[('All', 60)]
    lines += [r'\midrule', f'All pairs & & & [{r.simultaneous_lower:.4f}, {r.simultaneous_upper:.4f}] & & & & ' + r'\\', r'\bottomrule', r'\end{tabular}', r'\endgroup']
    head = '% Generated by research/r8_es_fz0/displays.py; do not edit.\n'
    num = head + ''.join(f'\\newcommand{{\\nEs{k}}}{{{v}}}\n' for k, v in m.items())
    return num, head + '\n'.join(lines) + '\n'

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    num, tab = build(); targets = {OUT / 'numbers_es.tex': num, OUT / 'tab_es.tex': tab}
    if a.check:
        bad = [str(p) for p, t in targets.items() if not p.exists() or p.read_text() != t]
        print(json.dumps(dict(status='pass' if not bad else 'FAIL', stale=bad))); sys.exit(1 if bad else 0)
    for p, t in targets.items(): p.write_text(t)
    rec = dict(inputs={n: hashlib.sha256((ART / n).read_bytes()).hexdigest() for n in ['summary.csv', 'contrasts.csv', 'run.json']},
               outputs={p.name: hashlib.sha256(t.encode()).hexdigest() for p, t in targets.items()})
    (ART / 'displays.json').write_text(json.dumps(rec, indent=2) + '\n'); print('written')
if __name__ == '__main__': main()
