"""Manuscript displays of the stepdown and model-confidence-set study.

Reads artifacts/r8_romano_wolf/{results,critical_values,mcs}.csv; writes
source/sections_r8/numbers_rw.tex and tab_rw.tex. --check compares regenerated displays with disk.
"""
import argparse, hashlib, json, sys
from pathlib import Path
import pandas as pd
ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / 'artifacts/r8_romano_wolf'; OUT = ROOT / 'source/sections_r8'
LABEL = {'Raw': 'Raw', 'Vol-ERM': 'Vol-ERM', 'State-L1': 'Regularised state', 'POT-Shift': 'POT-Shift', 'POT-Vol': 'POT-Vol',
         'DtACI-projected-expected': 'Projected DtACI', 'Loss-gate': 'Loss gate', 'Past-minimum': 'Past-loss minimum'}
TAG = {'Raw': 'Raw', 'Vol-ERM': 'VolErm', 'State-L1': 'Lone', 'POT-Shift': 'Pot', 'POT-Vol': 'PotVol',
       'DtACI-projected-expected': 'Dtaci', 'Loss-gate': 'Gate', 'Past-minimum': 'Past'}


def build():
    r = pd.read_csv(ART / 'results.csv'); c = pd.read_csv(ART / 'critical_values.csv'); m = pd.read_csv(ART / 'mcs.csv')
    rows, mac = [], {}
    for name in LABEL:
        a = r[(r.method == name) & (r.block_calendar_days == 20)].iloc[0]; b = r[(r.method == name) & (r.block_calendar_days == 60)].iloc[0]
        st = lambda x: 'none' if x.stepdown_step == 0 else str(int(x.stepdown_step))
        rows.append(f'{LABEL[name]} & {a.difference:.4f} & {a.t:.2f} & {st(a)} & {b.t:.2f} & {st(b)} \\\\')
        mac[f'RW{TAG[name]}TTwenty'] = f'{a.t:.2f}'; mac[f'RW{TAG[name]}TSixty'] = f'{b.t:.2f}'
    for block, word in [(20, 'Twenty'), (60, 'Sixty')]:
        cc = c[c.block_calendar_days == block].iloc[0]
        mac[f'RWCritEight{word}'] = f'{cc.eight_member_critical:.3f}'; mac[f'RWCritSix{word}'] = f'{cc.six_member_critical:.3f}'
        mac[f'RWRawSixLo{word}'] = f'{-cc.raw_band_upper_six_critical:.4f}'; mac[f'RWRawSixHi{word}'] = f'{-cc.raw_band_lower_six_critical:.4f}'
        rr = r[r.block_calendar_days == block]
        mac[f'RWRejected{word}'] = str(int(rr.rejected_stepdown.sum()))
        rejected = rr[rr.rejected_stepdown].method.tolist()
        assert rejected == ['DtACI-projected-expected'], (block, rejected)
        for statistic, tag in [('range', ''), ('max', 'Max')]:
            mm = m[(m.block_calendar_days == block) & (m.statistic == statistic)]
            elim = [e for e in mm.eliminated.fillna('') if e]
            last = mm.iloc[-1]
            mac[f'RWMcs{tag}Size{word}'] = str(int(last['size']) - (1 if isinstance(last.eliminated, str) and last.eliminated else 0))
            mac[f'RWMcs{tag}Eliminated{word}'] = str(len(elim))
            raw_row = mm[mm.members.str.contains('Raw')].iloc[-1]
            mac[f'RWMcs{tag}RawP{word}'] = f'{float(raw_row.mcs_p_value):.3f}'
            mac[f'RWMcs{tag}StopP{word}'] = f'{float(last.p_value):.3f}'
    rng = lambda b: [e for e in m[(m.block_calendar_days == b) & (m.statistic == 'range')].eliminated.fillna('') if e]
    mx = lambda b: [e for e in m[(m.block_calendar_days == b) & (m.statistic == 'max')].eliminated.fillna('') if e]
    assert rng(20) == ['DtACI-projected-expected', 'Raw'] and rng(60) == ['DtACI-projected-expected', 'Raw'], (rng(20), rng(60))
    assert mx(20) == ['DtACI-projected-expected', 'Raw'] and mx(60) == ['DtACI-projected-expected'], (mx(20), mx(60))
    tab = ('% Generated by research/r8_romano_wolf/displays.py; do not edit.\n'
           '\\begin{tabular}{lrrlrl}\n\\toprule\n'
           '& & \\multicolumn{2}{c}{20-day blocks} & \\multicolumn{2}{c}{60-day blocks} \\\\\n'
           '\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\n'
           'Method & Difference & $t$ & Rejected at step & $t$ & Rejected at step \\\\\n\\midrule\n'
           + '\n'.join(rows) + '\n\\bottomrule\n\\end{tabular}\n')
    num = '% Generated by research/r8_romano_wolf/displays.py; do not edit.\n' + ''.join(f'\\newcommand{{\\n{k}}}{{{v}}}\n' for k, v in mac.items())
    return num, tab


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    num, tab = build()
    targets = {OUT / 'numbers_rw.tex': num, OUT / 'tab_rw.tex': tab}
    if a.check:
        bad = [str(p) for p, t in targets.items() if not p.exists() or p.read_text() != t]
        print(json.dumps(dict(status='pass' if not bad else 'FAIL', stale=bad))); sys.exit(1 if bad else 0)
    for p, t in targets.items(): p.write_text(t)
    rec = dict(inputs={n: hashlib.sha256((ART / n).read_bytes()).hexdigest() for n in ['results.csv', 'critical_values.csv', 'mcs.csv']},
               outputs={p.name: hashlib.sha256(t.encode()).hexdigest() for p, t in targets.items()})
    (ART / 'displays.json').write_text(json.dumps(rec, indent=2) + '\n'); print(json.dumps(rec, indent=2))
if __name__ == '__main__': main()
