"""Manuscript displays of the panel-level violation-rate study.

Reads artifacts/r8_coverage_panel/coverage.csv; writes source/sections_r8/numbers_coverage.tex
and tab_coverage.tex. --check regenerates into memory and compares with the files on disk.
"""
import argparse, hashlib, json, sys
from pathlib import Path
import pandas as pd
ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / 'artifacts/r8_coverage_panel'; OUT = ROOT / 'source/sections_r8'
LABEL = {'Raw': 'Raw', 'Shift-CP': 'Shift-CP', 'Rolling250': 'Rolling 250', 'Rolling500': 'Rolling 500',
         'Selected-rolling': 'Selected rolling', 'Gate-selected-rolling': 'Coverage-gated rolling',
         'Loss-gate': 'Loss gate', 'Past-minimum': 'Past-loss minimum'}
TAG = {'Raw': 'Raw', 'Shift-CP': 'Static', 'Rolling250': 'Rolling', 'Rolling500': 'RollingLong',
       'Selected-rolling': 'Selected', 'Gate-selected-rolling': 'Gated', 'Loss-gate': 'Gate', 'Past-minimum': 'Past'}


def build():
    c = pd.read_csv(ART / 'coverage.csv')
    rows, mac = [], {}
    for m in LABEL:
        a = c[(c.method == m) & (c.block_calendar_days == 20)].iloc[0]
        b = c[(c.method == m) & (c.block_calendar_days == 60)].iloc[0]
        assert a.independence_undefined == 0 and a.joint_undefined == 0 and a.kupiec_undefined == 0
        rows.append(f'{LABEL[m]} & {a.violation_rate_pct:.3f} & [{a.lower_pct:.3f}, {a.upper_pct:.3f}] & [{b.lower_pct:.3f}, {b.upper_pct:.3f}] & {int(a.kupiec_rejections)} & {int(a.independence_rejections)} & {int(a.joint_rejections)} \\\\')
        t = TAG[m]
        mac[f'Cov{t}Pi'] = f'{a.violation_rate_pct:.3f}'
        mac[f'Cov{t}TwentyLo'] = f'{a.lower_pct:.3f}'; mac[f'Cov{t}TwentyHi'] = f'{a.upper_pct:.3f}'
        mac[f'Cov{t}SixtyLo'] = f'{b.lower_pct:.3f}'; mac[f'Cov{t}SixtyHi'] = f'{b.upper_pct:.3f}'
        mac[f'Cov{t}Kup'] = str(int(a.kupiec_rejections)); mac[f'Cov{t}Ind'] = str(int(a.independence_rejections)); mac[f'Cov{t}CC'] = str(int(a.joint_rejections))
    mac['CovExcludeNominal'] = str(int(c[c.block_calendar_days == 60].excludes_nominal.sum()))
    mac['CovMethods'] = str(len(LABEL)); mac['CovDraws'] = str(int(c.draws.iloc[0]))
    tab = ('% Generated by research/r8_coverage_panel/displays.py; do not edit.\n'
           '\\begingroup\\setlength{\\tabcolsep}{3pt}\n\\begin{tabular}{lrrrrrr}\n\\toprule\n'
           'Method & Violations (\\%) & 20-day interval & 60-day interval & UC & Ind. & CC \\\\\n\\midrule\n'
           + '\n'.join(rows) + '\n\\bottomrule\n\\end{tabular}\n\\endgroup\n')
    num = '% Generated by research/r8_coverage_panel/displays.py; do not edit.\n' + ''.join(f'\\newcommand{{\\n{k}}}{{{v}}}\n' for k, v in mac.items())
    return num, tab


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args()
    num, tab = build()
    targets = {OUT / 'numbers_coverage.tex': num, OUT / 'tab_coverage.tex': tab}
    if a.check:
        bad = [str(p) for p, t in targets.items() if not p.exists() or p.read_text() != t]
        print(json.dumps(dict(status='pass' if not bad else 'FAIL', stale=bad))); sys.exit(1 if bad else 0)
    for p, t in targets.items(): p.write_text(t)
    rec = dict(inputs={'coverage.csv': hashlib.sha256((ART / 'coverage.csv').read_bytes()).hexdigest()},
               outputs={p.name: hashlib.sha256(t.encode()).hexdigest() for p, t in targets.items()})
    (ART / 'displays.json').write_text(json.dumps(rec, indent=2) + '\n'); print(json.dumps(rec, indent=2))
if __name__ == '__main__': main()
